// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module blendOpt_480_640_s (
        imageA_rows_dout,
        imageA_rows_empty_n,
        imageA_rows_read,
        imageA_cols_dout,
        imageA_cols_empty_n,
        imageA_cols_read,
        imageA_data_V_dout,
        imageA_data_V_empty_n,
        imageA_data_V_read,
        imageB_data_V_dout,
        imageB_data_V_empty_n,
        imageB_data_V_read,
        imageS_data_V_din,
        imageS_data_V_full_n,
        imageS_data_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [8:0] imageA_rows_dout;
input   imageA_rows_empty_n;
output   imageA_rows_read;
input  [9:0] imageA_cols_dout;
input   imageA_cols_empty_n;
output   imageA_cols_read;
input  [7:0] imageA_data_V_dout;
input   imageA_data_V_empty_n;
output   imageA_data_V_read;
input  [7:0] imageB_data_V_dout;
input   imageB_data_V_empty_n;
output   imageB_data_V_read;
output  [7:0] imageS_data_V_din;
input   imageS_data_V_full_n;
output   imageS_data_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    blendOpt_Block_proc_U0_ap_start;
wire    blendOpt_Block_proc_U0_ap_done;
wire    blendOpt_Block_proc_U0_ap_continue;
wire    blendOpt_Block_proc_U0_ap_idle;
wire    blendOpt_Block_proc_U0_ap_ready;
wire    blendOpt_Block_proc_U0_imageA_rows_read;
wire    blendOpt_Block_proc_U0_imageA_cols_read;
wire   [8:0] blendOpt_Block_proc_U0_imageA_rows_load3_out_out_din;
wire    blendOpt_Block_proc_U0_imageA_rows_load3_out_out_write;
wire   [9:0] blendOpt_Block_proc_U0_imageA_cols_load4_out_out_din;
wire    blendOpt_Block_proc_U0_imageA_cols_load4_out_out_write;
wire    blendOpt_Loop_1_proc_U0_ap_start;
wire    blendOpt_Loop_1_proc_U0_ap_done;
wire    blendOpt_Loop_1_proc_U0_ap_continue;
wire    blendOpt_Loop_1_proc_U0_ap_idle;
wire    blendOpt_Loop_1_proc_U0_ap_ready;
wire    blendOpt_Loop_1_proc_U0_start_out;
wire    blendOpt_Loop_1_proc_U0_start_write;
wire    blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_read;
wire    blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_read;
wire    blendOpt_Loop_1_proc_U0_imageA_data_V_read;
wire   [7:0] blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_din;
wire    blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_write;
wire    blendOpt_Loop_1_proc_U0_imageB_data_V_read;
wire   [7:0] blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_din;
wire    blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_write;
wire   [8:0] blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_din;
wire    blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_write;
wire   [9:0] blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_din;
wire    blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_write;
wire    xFPyrDownGaussianBlu_1_U0_ap_start;
wire    xFPyrDownGaussianBlu_1_U0_ap_done;
wire    xFPyrDownGaussianBlu_1_U0_ap_continue;
wire    xFPyrDownGaussianBlu_1_U0_ap_idle;
wire    xFPyrDownGaussianBlu_1_U0_ap_ready;
wire    xFPyrDownGaussianBlu_1_U0_start_out;
wire    xFPyrDownGaussianBlu_1_U0_start_write;
wire    xFPyrDownGaussianBlu_1_U0_p_src_A_V_V_read;
wire    xFPyrDownGaussianBlu_1_U0_p_src_B_V_V_read;
wire   [7:0] xFPyrDownGaussianBlu_1_U0_p_dst_V_V_din;
wire    xFPyrDownGaussianBlu_1_U0_p_dst_V_V_write;
wire    xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_read;
wire    xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_read;
wire   [8:0] xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_din;
wire    xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_write;
wire   [9:0] xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_din;
wire    xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_write;
wire    blendOpt_Loop_2_proc_U0_ap_start;
wire    blendOpt_Loop_2_proc_U0_ap_done;
wire    blendOpt_Loop_2_proc_U0_ap_continue;
wire    blendOpt_Loop_2_proc_U0_ap_idle;
wire    blendOpt_Loop_2_proc_U0_ap_ready;
wire    blendOpt_Loop_2_proc_U0_imageA_rows_load3_loc_read;
wire    blendOpt_Loop_2_proc_U0_imageA_cols_load4_loc_read;
wire    blendOpt_Loop_2_proc_U0_p_imageS_out_V_V_read;
wire   [7:0] blendOpt_Loop_2_proc_U0_imageS_data_V_din;
wire    blendOpt_Loop_2_proc_U0_imageS_data_V_write;
wire    ap_sync_continue;
wire    imageA_rows_load3_lo_4_full_n;
wire   [8:0] imageA_rows_load3_lo_4_dout;
wire    imageA_rows_load3_lo_4_empty_n;
wire    imageA_cols_load4_lo_4_full_n;
wire   [9:0] imageA_cols_load4_lo_4_dout;
wire    imageA_cols_load4_lo_4_empty_n;
wire    p_imageA_in_V_V_full_n;
wire   [7:0] p_imageA_in_V_V_dout;
wire    p_imageA_in_V_V_empty_n;
wire    p_imageB_in_V_V_full_n;
wire   [7:0] p_imageB_in_V_V_dout;
wire    p_imageB_in_V_V_empty_n;
wire    imageA_rows_load3_lo_3_full_n;
wire   [8:0] imageA_rows_load3_lo_3_dout;
wire    imageA_rows_load3_lo_3_empty_n;
wire    imageA_cols_load4_lo_3_full_n;
wire   [9:0] imageA_cols_load4_lo_3_dout;
wire    imageA_cols_load4_lo_3_empty_n;
wire    p_imageS_out_V_V_full_n;
wire   [7:0] p_imageS_out_V_V_dout;
wire    p_imageS_out_V_V_empty_n;
wire    imageA_rows_load3_lo_full_n;
wire   [8:0] imageA_rows_load3_lo_dout;
wire    imageA_rows_load3_lo_empty_n;
wire    imageA_cols_load4_lo_full_n;
wire   [9:0] imageA_cols_load4_lo_dout;
wire    imageA_cols_load4_lo_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_blendOpt_Block_proc_U0_ap_ready;
wire    ap_sync_blendOpt_Block_proc_U0_ap_ready;
reg   [1:0] blendOpt_Block_proc_U0_ap_ready_count;
reg    ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready;
wire    ap_sync_blendOpt_Loop_1_proc_U0_ap_ready;
reg   [1:0] blendOpt_Loop_1_proc_U0_ap_ready_count;
wire    blendOpt_Block_proc_U0_start_full_n;
wire    blendOpt_Block_proc_U0_start_write;
wire   [0:0] start_for_xFPyrDownGaussianBlu_1_U0_din;
wire    start_for_xFPyrDownGaussianBlu_1_U0_full_n;
wire   [0:0] start_for_xFPyrDownGaussianBlu_1_U0_dout;
wire    start_for_xFPyrDownGaussianBlu_1_U0_empty_n;
wire   [0:0] start_for_blendOpt_Loop_2_proc_U0_din;
wire    start_for_blendOpt_Loop_2_proc_U0_full_n;
wire   [0:0] start_for_blendOpt_Loop_2_proc_U0_dout;
wire    start_for_blendOpt_Loop_2_proc_U0_empty_n;
wire    blendOpt_Loop_2_proc_U0_start_full_n;
wire    blendOpt_Loop_2_proc_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_blendOpt_Block_proc_U0_ap_ready = 1'b0;
#0 blendOpt_Block_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready = 1'b0;
#0 blendOpt_Loop_1_proc_U0_ap_ready_count = 2'd0;
end

blendOpt_Block_proc blendOpt_Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blendOpt_Block_proc_U0_ap_start),
    .ap_done(blendOpt_Block_proc_U0_ap_done),
    .ap_continue(blendOpt_Block_proc_U0_ap_continue),
    .ap_idle(blendOpt_Block_proc_U0_ap_idle),
    .ap_ready(blendOpt_Block_proc_U0_ap_ready),
    .imageA_rows_dout(imageA_rows_dout),
    .imageA_rows_empty_n(imageA_rows_empty_n),
    .imageA_rows_read(blendOpt_Block_proc_U0_imageA_rows_read),
    .imageA_cols_dout(imageA_cols_dout),
    .imageA_cols_empty_n(imageA_cols_empty_n),
    .imageA_cols_read(blendOpt_Block_proc_U0_imageA_cols_read),
    .imageA_rows_load3_out_out_din(blendOpt_Block_proc_U0_imageA_rows_load3_out_out_din),
    .imageA_rows_load3_out_out_full_n(imageA_rows_load3_lo_4_full_n),
    .imageA_rows_load3_out_out_write(blendOpt_Block_proc_U0_imageA_rows_load3_out_out_write),
    .imageA_cols_load4_out_out_din(blendOpt_Block_proc_U0_imageA_cols_load4_out_out_din),
    .imageA_cols_load4_out_out_full_n(imageA_cols_load4_lo_4_full_n),
    .imageA_cols_load4_out_out_write(blendOpt_Block_proc_U0_imageA_cols_load4_out_out_write)
);

blendOpt_Loop_1_proc blendOpt_Loop_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blendOpt_Loop_1_proc_U0_ap_start),
    .start_full_n(start_for_xFPyrDownGaussianBlu_1_U0_full_n),
    .ap_done(blendOpt_Loop_1_proc_U0_ap_done),
    .ap_continue(blendOpt_Loop_1_proc_U0_ap_continue),
    .ap_idle(blendOpt_Loop_1_proc_U0_ap_idle),
    .ap_ready(blendOpt_Loop_1_proc_U0_ap_ready),
    .start_out(blendOpt_Loop_1_proc_U0_start_out),
    .start_write(blendOpt_Loop_1_proc_U0_start_write),
    .imageA_rows_load3_loc_dout(imageA_rows_load3_lo_4_dout),
    .imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_4_empty_n),
    .imageA_rows_load3_loc_read(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_read),
    .imageA_cols_load4_loc_dout(imageA_cols_load4_lo_4_dout),
    .imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_4_empty_n),
    .imageA_cols_load4_loc_read(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_read),
    .imageA_data_V_dout(imageA_data_V_dout),
    .imageA_data_V_empty_n(imageA_data_V_empty_n),
    .imageA_data_V_read(blendOpt_Loop_1_proc_U0_imageA_data_V_read),
    .p_imageA_in_V_V_din(blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_din),
    .p_imageA_in_V_V_full_n(p_imageA_in_V_V_full_n),
    .p_imageA_in_V_V_write(blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_write),
    .imageB_data_V_dout(imageB_data_V_dout),
    .imageB_data_V_empty_n(imageB_data_V_empty_n),
    .imageB_data_V_read(blendOpt_Loop_1_proc_U0_imageB_data_V_read),
    .p_imageB_in_V_V_din(blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_din),
    .p_imageB_in_V_V_full_n(p_imageB_in_V_V_full_n),
    .p_imageB_in_V_V_write(blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_write),
    .imageA_rows_load3_loc_out_din(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_din),
    .imageA_rows_load3_loc_out_full_n(imageA_rows_load3_lo_3_full_n),
    .imageA_rows_load3_loc_out_write(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_write),
    .imageA_cols_load4_loc_out_din(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_din),
    .imageA_cols_load4_loc_out_full_n(imageA_cols_load4_lo_3_full_n),
    .imageA_cols_load4_loc_out_write(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_write)
);

xFPyrDownGaussianBlu_1 xFPyrDownGaussianBlu_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFPyrDownGaussianBlu_1_U0_ap_start),
    .start_full_n(start_for_blendOpt_Loop_2_proc_U0_full_n),
    .ap_done(xFPyrDownGaussianBlu_1_U0_ap_done),
    .ap_continue(xFPyrDownGaussianBlu_1_U0_ap_continue),
    .ap_idle(xFPyrDownGaussianBlu_1_U0_ap_idle),
    .ap_ready(xFPyrDownGaussianBlu_1_U0_ap_ready),
    .start_out(xFPyrDownGaussianBlu_1_U0_start_out),
    .start_write(xFPyrDownGaussianBlu_1_U0_start_write),
    .p_src_A_V_V_dout(p_imageA_in_V_V_dout),
    .p_src_A_V_V_empty_n(p_imageA_in_V_V_empty_n),
    .p_src_A_V_V_read(xFPyrDownGaussianBlu_1_U0_p_src_A_V_V_read),
    .p_src_B_V_V_dout(p_imageB_in_V_V_dout),
    .p_src_B_V_V_empty_n(p_imageB_in_V_V_empty_n),
    .p_src_B_V_V_read(xFPyrDownGaussianBlu_1_U0_p_src_B_V_V_read),
    .p_dst_V_V_din(xFPyrDownGaussianBlu_1_U0_p_dst_V_V_din),
    .p_dst_V_V_full_n(p_imageS_out_V_V_full_n),
    .p_dst_V_V_write(xFPyrDownGaussianBlu_1_U0_p_dst_V_V_write),
    .imageA_rows_load3_loc_dout(imageA_rows_load3_lo_3_dout),
    .imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_3_empty_n),
    .imageA_rows_load3_loc_read(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_read),
    .imageA_cols_load4_loc_dout(imageA_cols_load4_lo_3_dout),
    .imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_3_empty_n),
    .imageA_cols_load4_loc_read(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_read),
    .imageA_rows_load3_loc_out_din(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_din),
    .imageA_rows_load3_loc_out_full_n(imageA_rows_load3_lo_full_n),
    .imageA_rows_load3_loc_out_write(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_write),
    .imageA_cols_load4_loc_out_din(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_din),
    .imageA_cols_load4_loc_out_full_n(imageA_cols_load4_lo_full_n),
    .imageA_cols_load4_loc_out_write(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_write)
);

blendOpt_Loop_2_proc blendOpt_Loop_2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blendOpt_Loop_2_proc_U0_ap_start),
    .ap_done(blendOpt_Loop_2_proc_U0_ap_done),
    .ap_continue(blendOpt_Loop_2_proc_U0_ap_continue),
    .ap_idle(blendOpt_Loop_2_proc_U0_ap_idle),
    .ap_ready(blendOpt_Loop_2_proc_U0_ap_ready),
    .imageA_rows_load3_loc_dout(imageA_rows_load3_lo_dout),
    .imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_empty_n),
    .imageA_rows_load3_loc_read(blendOpt_Loop_2_proc_U0_imageA_rows_load3_loc_read),
    .imageA_cols_load4_loc_dout(imageA_cols_load4_lo_dout),
    .imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_empty_n),
    .imageA_cols_load4_loc_read(blendOpt_Loop_2_proc_U0_imageA_cols_load4_loc_read),
    .p_imageS_out_V_V_dout(p_imageS_out_V_V_dout),
    .p_imageS_out_V_V_empty_n(p_imageS_out_V_V_empty_n),
    .p_imageS_out_V_V_read(blendOpt_Loop_2_proc_U0_p_imageS_out_V_V_read),
    .imageS_data_V_din(blendOpt_Loop_2_proc_U0_imageS_data_V_din),
    .imageS_data_V_full_n(imageS_data_V_full_n),
    .imageS_data_V_write(blendOpt_Loop_2_proc_U0_imageS_data_V_write)
);

fifo_w9_d2_A imageA_rows_load3_lo_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Block_proc_U0_imageA_rows_load3_out_out_din),
    .if_full_n(imageA_rows_load3_lo_4_full_n),
    .if_write(blendOpt_Block_proc_U0_imageA_rows_load3_out_out_write),
    .if_dout(imageA_rows_load3_lo_4_dout),
    .if_empty_n(imageA_rows_load3_lo_4_empty_n),
    .if_read(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_read)
);

fifo_w10_d2_A_x imageA_cols_load4_lo_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Block_proc_U0_imageA_cols_load4_out_out_din),
    .if_full_n(imageA_cols_load4_lo_4_full_n),
    .if_write(blendOpt_Block_proc_U0_imageA_cols_load4_out_out_write),
    .if_dout(imageA_cols_load4_lo_4_dout),
    .if_empty_n(imageA_cols_load4_lo_4_empty_n),
    .if_read(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_read)
);

fifo_w8_d2_A_x p_imageA_in_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_din),
    .if_full_n(p_imageA_in_V_V_full_n),
    .if_write(blendOpt_Loop_1_proc_U0_p_imageA_in_V_V_write),
    .if_dout(p_imageA_in_V_V_dout),
    .if_empty_n(p_imageA_in_V_V_empty_n),
    .if_read(xFPyrDownGaussianBlu_1_U0_p_src_A_V_V_read)
);

fifo_w8_d2_A_x p_imageB_in_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_din),
    .if_full_n(p_imageB_in_V_V_full_n),
    .if_write(blendOpt_Loop_1_proc_U0_p_imageB_in_V_V_write),
    .if_dout(p_imageB_in_V_V_dout),
    .if_empty_n(p_imageB_in_V_V_empty_n),
    .if_read(xFPyrDownGaussianBlu_1_U0_p_src_B_V_V_read)
);

fifo_w9_d2_A imageA_rows_load3_lo_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_din),
    .if_full_n(imageA_rows_load3_lo_3_full_n),
    .if_write(blendOpt_Loop_1_proc_U0_imageA_rows_load3_loc_out_write),
    .if_dout(imageA_rows_load3_lo_3_dout),
    .if_empty_n(imageA_rows_load3_lo_3_empty_n),
    .if_read(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_read)
);

fifo_w10_d2_A_x imageA_cols_load4_lo_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_din),
    .if_full_n(imageA_cols_load4_lo_3_full_n),
    .if_write(blendOpt_Loop_1_proc_U0_imageA_cols_load4_loc_out_write),
    .if_dout(imageA_cols_load4_lo_3_dout),
    .if_empty_n(imageA_cols_load4_lo_3_empty_n),
    .if_read(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_read)
);

fifo_w8_d2_A_x p_imageS_out_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFPyrDownGaussianBlu_1_U0_p_dst_V_V_din),
    .if_full_n(p_imageS_out_V_V_full_n),
    .if_write(xFPyrDownGaussianBlu_1_U0_p_dst_V_V_write),
    .if_dout(p_imageS_out_V_V_dout),
    .if_empty_n(p_imageS_out_V_V_empty_n),
    .if_read(blendOpt_Loop_2_proc_U0_p_imageS_out_V_V_read)
);

fifo_w9_d2_A imageA_rows_load3_lo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_din),
    .if_full_n(imageA_rows_load3_lo_full_n),
    .if_write(xFPyrDownGaussianBlu_1_U0_imageA_rows_load3_loc_out_write),
    .if_dout(imageA_rows_load3_lo_dout),
    .if_empty_n(imageA_rows_load3_lo_empty_n),
    .if_read(blendOpt_Loop_2_proc_U0_imageA_rows_load3_loc_read)
);

fifo_w10_d2_A_x imageA_cols_load4_lo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_din),
    .if_full_n(imageA_cols_load4_lo_full_n),
    .if_write(xFPyrDownGaussianBlu_1_U0_imageA_cols_load4_loc_out_write),
    .if_dout(imageA_cols_load4_lo_dout),
    .if_empty_n(imageA_cols_load4_lo_empty_n),
    .if_read(blendOpt_Loop_2_proc_U0_imageA_cols_load4_loc_read)
);

start_for_xFPyrDoGfk start_for_xFPyrDoGfk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFPyrDownGaussianBlu_1_U0_din),
    .if_full_n(start_for_xFPyrDownGaussianBlu_1_U0_full_n),
    .if_write(blendOpt_Loop_1_proc_U0_start_write),
    .if_dout(start_for_xFPyrDownGaussianBlu_1_U0_dout),
    .if_empty_n(start_for_xFPyrDownGaussianBlu_1_U0_empty_n),
    .if_read(xFPyrDownGaussianBlu_1_U0_ap_ready)
);

start_for_blendOpHfu start_for_blendOpHfu_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_blendOpt_Loop_2_proc_U0_din),
    .if_full_n(start_for_blendOpt_Loop_2_proc_U0_full_n),
    .if_write(xFPyrDownGaussianBlu_1_U0_start_write),
    .if_dout(start_for_blendOpt_Loop_2_proc_U0_dout),
    .if_empty_n(start_for_blendOpt_Loop_2_proc_U0_empty_n),
    .if_read(blendOpt_Loop_2_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_blendOpt_Block_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_blendOpt_Block_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_blendOpt_Block_proc_U0_ap_ready <= ap_sync_blendOpt_Block_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready <= ap_sync_blendOpt_Loop_1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((blendOpt_Block_proc_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        blendOpt_Block_proc_U0_ap_ready_count <= (blendOpt_Block_proc_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (blendOpt_Block_proc_U0_ap_ready == 1'b1))) begin
        blendOpt_Block_proc_U0_ap_ready_count <= (blendOpt_Block_proc_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((blendOpt_Loop_1_proc_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        blendOpt_Loop_1_proc_U0_ap_ready_count <= (blendOpt_Loop_1_proc_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (blendOpt_Loop_1_proc_U0_ap_ready == 1'b1))) begin
        blendOpt_Loop_1_proc_U0_ap_ready_count <= (blendOpt_Loop_1_proc_U0_ap_ready_count + 2'd1);
    end
end

assign ap_done = blendOpt_Loop_2_proc_U0_ap_done;

assign ap_idle = (xFPyrDownGaussianBlu_1_U0_ap_idle & blendOpt_Loop_2_proc_U0_ap_idle & blendOpt_Loop_1_proc_U0_ap_idle & blendOpt_Block_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_blendOpt_Block_proc_U0_ap_ready = (blendOpt_Block_proc_U0_ap_ready | ap_sync_reg_blendOpt_Block_proc_U0_ap_ready);

assign ap_sync_blendOpt_Loop_1_proc_U0_ap_ready = (blendOpt_Loop_1_proc_U0_ap_ready | ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = blendOpt_Loop_2_proc_U0_ap_done;

assign ap_sync_ready = (ap_sync_blendOpt_Loop_1_proc_U0_ap_ready & ap_sync_blendOpt_Block_proc_U0_ap_ready);

assign blendOpt_Block_proc_U0_ap_continue = 1'b1;

assign blendOpt_Block_proc_U0_ap_start = ((ap_sync_reg_blendOpt_Block_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign blendOpt_Block_proc_U0_start_full_n = 1'b1;

assign blendOpt_Block_proc_U0_start_write = 1'b0;

assign blendOpt_Loop_1_proc_U0_ap_continue = 1'b1;

assign blendOpt_Loop_1_proc_U0_ap_start = ((ap_sync_reg_blendOpt_Loop_1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign blendOpt_Loop_2_proc_U0_ap_continue = ap_continue;

assign blendOpt_Loop_2_proc_U0_ap_start = start_for_blendOpt_Loop_2_proc_U0_empty_n;

assign blendOpt_Loop_2_proc_U0_start_full_n = 1'b1;

assign blendOpt_Loop_2_proc_U0_start_write = 1'b0;

assign imageA_cols_read = blendOpt_Block_proc_U0_imageA_cols_read;

assign imageA_data_V_read = blendOpt_Loop_1_proc_U0_imageA_data_V_read;

assign imageA_rows_read = blendOpt_Block_proc_U0_imageA_rows_read;

assign imageB_data_V_read = blendOpt_Loop_1_proc_U0_imageB_data_V_read;

assign imageS_data_V_din = blendOpt_Loop_2_proc_U0_imageS_data_V_din;

assign imageS_data_V_write = blendOpt_Loop_2_proc_U0_imageS_data_V_write;

assign start_for_blendOpt_Loop_2_proc_U0_din = 1'b1;

assign start_for_xFPyrDownGaussianBlu_1_U0_din = 1'b1;

assign xFPyrDownGaussianBlu_1_U0_ap_continue = 1'b1;

assign xFPyrDownGaussianBlu_1_U0_ap_start = start_for_xFPyrDownGaussianBlu_1_U0_empty_n;

endmodule //blendOpt_480_640_s
