// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "blendOpt_480_640_83.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic blendOpt_480_640_83::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> blendOpt_480_640_83::ap_const_lv8_0 = "00000000";
const sc_logic blendOpt_480_640_83::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<2> blendOpt_480_640_83::ap_const_lv2_0 = "00";
const sc_lv<2> blendOpt_480_640_83::ap_const_lv2_1 = "1";
const bool blendOpt_480_640_83::ap_const_boolean_1 = true;

blendOpt_480_640_83::blendOpt_480_640_83(sc_module_name name) : sc_module(name), mVcdFile(0) {
    blendOpt83_Block_pr_U0 = new blendOpt83_Block_pr("blendOpt83_Block_pr_U0");
    blendOpt83_Block_pr_U0->ap_clk(ap_clk);
    blendOpt83_Block_pr_U0->ap_rst(ap_rst);
    blendOpt83_Block_pr_U0->ap_start(blendOpt83_Block_pr_U0_ap_start);
    blendOpt83_Block_pr_U0->ap_done(blendOpt83_Block_pr_U0_ap_done);
    blendOpt83_Block_pr_U0->ap_continue(blendOpt83_Block_pr_U0_ap_continue);
    blendOpt83_Block_pr_U0->ap_idle(blendOpt83_Block_pr_U0_ap_idle);
    blendOpt83_Block_pr_U0->ap_ready(blendOpt83_Block_pr_U0_ap_ready);
    blendOpt83_Block_pr_U0->imageA_rows_dout(imageA_rows_dout);
    blendOpt83_Block_pr_U0->imageA_rows_empty_n(imageA_rows_empty_n);
    blendOpt83_Block_pr_U0->imageA_rows_read(blendOpt83_Block_pr_U0_imageA_rows_read);
    blendOpt83_Block_pr_U0->imageA_cols_dout(imageA_cols_dout);
    blendOpt83_Block_pr_U0->imageA_cols_empty_n(imageA_cols_empty_n);
    blendOpt83_Block_pr_U0->imageA_cols_read(blendOpt83_Block_pr_U0_imageA_cols_read);
    blendOpt83_Block_pr_U0->imageA_rows_load3_out_out_din(blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_din);
    blendOpt83_Block_pr_U0->imageA_rows_load3_out_out_full_n(imageA_rows_load3_lo_2_full_n);
    blendOpt83_Block_pr_U0->imageA_rows_load3_out_out_write(blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_write);
    blendOpt83_Block_pr_U0->imageA_cols_load4_out_out_din(blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_din);
    blendOpt83_Block_pr_U0->imageA_cols_load4_out_out_full_n(imageA_cols_load4_lo_2_full_n);
    blendOpt83_Block_pr_U0->imageA_cols_load4_out_out_write(blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_write);
    blendOpt83_Loop_1_pr_U0 = new blendOpt83_Loop_1_pr("blendOpt83_Loop_1_pr_U0");
    blendOpt83_Loop_1_pr_U0->ap_clk(ap_clk);
    blendOpt83_Loop_1_pr_U0->ap_rst(ap_rst);
    blendOpt83_Loop_1_pr_U0->ap_start(blendOpt83_Loop_1_pr_U0_ap_start);
    blendOpt83_Loop_1_pr_U0->start_full_n(start_for_xFPyrDownGaussianBlu_U0_full_n);
    blendOpt83_Loop_1_pr_U0->ap_done(blendOpt83_Loop_1_pr_U0_ap_done);
    blendOpt83_Loop_1_pr_U0->ap_continue(blendOpt83_Loop_1_pr_U0_ap_continue);
    blendOpt83_Loop_1_pr_U0->ap_idle(blendOpt83_Loop_1_pr_U0_ap_idle);
    blendOpt83_Loop_1_pr_U0->ap_ready(blendOpt83_Loop_1_pr_U0_ap_ready);
    blendOpt83_Loop_1_pr_U0->start_out(blendOpt83_Loop_1_pr_U0_start_out);
    blendOpt83_Loop_1_pr_U0->start_write(blendOpt83_Loop_1_pr_U0_start_write);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_dout(imageA_rows_load3_lo_2_dout);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_2_empty_n);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_read(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_read);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_dout(imageA_cols_load4_lo_2_dout);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_2_empty_n);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_read(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_read);
    blendOpt83_Loop_1_pr_U0->imageA_data_V_dout(imageA_data_V_dout);
    blendOpt83_Loop_1_pr_U0->imageA_data_V_empty_n(imageA_data_V_empty_n);
    blendOpt83_Loop_1_pr_U0->imageA_data_V_read(blendOpt83_Loop_1_pr_U0_imageA_data_V_read);
    blendOpt83_Loop_1_pr_U0->p_imageA_in_V_V_din(blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_din);
    blendOpt83_Loop_1_pr_U0->p_imageA_in_V_V_full_n(p_imageA_in_V_V_full_n);
    blendOpt83_Loop_1_pr_U0->p_imageA_in_V_V_write(blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_write);
    blendOpt83_Loop_1_pr_U0->imageB_data_V_dout(imageB_data_V_dout);
    blendOpt83_Loop_1_pr_U0->imageB_data_V_empty_n(imageB_data_V_empty_n);
    blendOpt83_Loop_1_pr_U0->imageB_data_V_read(blendOpt83_Loop_1_pr_U0_imageB_data_V_read);
    blendOpt83_Loop_1_pr_U0->p_imageB_in_V_V_din(blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_din);
    blendOpt83_Loop_1_pr_U0->p_imageB_in_V_V_full_n(p_imageB_in_V_V_full_n);
    blendOpt83_Loop_1_pr_U0->p_imageB_in_V_V_write(blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_write);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_out_din(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_din);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_out_full_n(imageA_rows_load3_lo_1_full_n);
    blendOpt83_Loop_1_pr_U0->imageA_rows_load3_loc_out_write(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_write);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_out_din(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_din);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_out_full_n(imageA_cols_load4_lo_1_full_n);
    blendOpt83_Loop_1_pr_U0->imageA_cols_load4_loc_out_write(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_write);
    xFPyrDownGaussianBlu_U0 = new xFPyrDownGaussianBlu("xFPyrDownGaussianBlu_U0");
    xFPyrDownGaussianBlu_U0->ap_clk(ap_clk);
    xFPyrDownGaussianBlu_U0->ap_rst(ap_rst);
    xFPyrDownGaussianBlu_U0->ap_start(xFPyrDownGaussianBlu_U0_ap_start);
    xFPyrDownGaussianBlu_U0->start_full_n(start_for_blendOpt83_Loop_2_pr_U0_full_n);
    xFPyrDownGaussianBlu_U0->ap_done(xFPyrDownGaussianBlu_U0_ap_done);
    xFPyrDownGaussianBlu_U0->ap_continue(xFPyrDownGaussianBlu_U0_ap_continue);
    xFPyrDownGaussianBlu_U0->ap_idle(xFPyrDownGaussianBlu_U0_ap_idle);
    xFPyrDownGaussianBlu_U0->ap_ready(xFPyrDownGaussianBlu_U0_ap_ready);
    xFPyrDownGaussianBlu_U0->start_out(xFPyrDownGaussianBlu_U0_start_out);
    xFPyrDownGaussianBlu_U0->start_write(xFPyrDownGaussianBlu_U0_start_write);
    xFPyrDownGaussianBlu_U0->p_imageA_in_V_V_dout(p_imageA_in_V_V_dout);
    xFPyrDownGaussianBlu_U0->p_imageA_in_V_V_empty_n(p_imageA_in_V_V_empty_n);
    xFPyrDownGaussianBlu_U0->p_imageA_in_V_V_read(xFPyrDownGaussianBlu_U0_p_imageA_in_V_V_read);
    xFPyrDownGaussianBlu_U0->p_imageB_in_V_V_dout(p_imageB_in_V_V_dout);
    xFPyrDownGaussianBlu_U0->p_imageB_in_V_V_empty_n(p_imageB_in_V_V_empty_n);
    xFPyrDownGaussianBlu_U0->p_imageB_in_V_V_read(xFPyrDownGaussianBlu_U0_p_imageB_in_V_V_read);
    xFPyrDownGaussianBlu_U0->p_imageS_out_V_V_din(xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_din);
    xFPyrDownGaussianBlu_U0->p_imageS_out_V_V_full_n(p_imageS_out_V_V_full_n);
    xFPyrDownGaussianBlu_U0->p_imageS_out_V_V_write(xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_write);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_dout(imageA_rows_load3_lo_1_dout);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_1_empty_n);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_read(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_read);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_dout(imageA_cols_load4_lo_1_dout);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_1_empty_n);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_read(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_read);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_out_din(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_din);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_out_full_n(imageA_rows_load3_lo_full_n);
    xFPyrDownGaussianBlu_U0->imageA_rows_load3_loc_out_write(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_write);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_out_din(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_din);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_out_full_n(imageA_cols_load4_lo_full_n);
    xFPyrDownGaussianBlu_U0->imageA_cols_load4_loc_out_write(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_write);
    blendOpt83_Loop_2_pr_U0 = new blendOpt83_Loop_2_pr("blendOpt83_Loop_2_pr_U0");
    blendOpt83_Loop_2_pr_U0->ap_clk(ap_clk);
    blendOpt83_Loop_2_pr_U0->ap_rst(ap_rst);
    blendOpt83_Loop_2_pr_U0->ap_start(blendOpt83_Loop_2_pr_U0_ap_start);
    blendOpt83_Loop_2_pr_U0->ap_done(blendOpt83_Loop_2_pr_U0_ap_done);
    blendOpt83_Loop_2_pr_U0->ap_continue(blendOpt83_Loop_2_pr_U0_ap_continue);
    blendOpt83_Loop_2_pr_U0->ap_idle(blendOpt83_Loop_2_pr_U0_ap_idle);
    blendOpt83_Loop_2_pr_U0->ap_ready(blendOpt83_Loop_2_pr_U0_ap_ready);
    blendOpt83_Loop_2_pr_U0->imageA_rows_load3_loc_dout(imageA_rows_load3_lo_dout);
    blendOpt83_Loop_2_pr_U0->imageA_rows_load3_loc_empty_n(imageA_rows_load3_lo_empty_n);
    blendOpt83_Loop_2_pr_U0->imageA_rows_load3_loc_read(blendOpt83_Loop_2_pr_U0_imageA_rows_load3_loc_read);
    blendOpt83_Loop_2_pr_U0->imageA_cols_load4_loc_dout(imageA_cols_load4_lo_dout);
    blendOpt83_Loop_2_pr_U0->imageA_cols_load4_loc_empty_n(imageA_cols_load4_lo_empty_n);
    blendOpt83_Loop_2_pr_U0->imageA_cols_load4_loc_read(blendOpt83_Loop_2_pr_U0_imageA_cols_load4_loc_read);
    blendOpt83_Loop_2_pr_U0->p_imageS_out_V_V_dout(p_imageS_out_V_V_dout);
    blendOpt83_Loop_2_pr_U0->p_imageS_out_V_V_empty_n(p_imageS_out_V_V_empty_n);
    blendOpt83_Loop_2_pr_U0->p_imageS_out_V_V_read(blendOpt83_Loop_2_pr_U0_p_imageS_out_V_V_read);
    blendOpt83_Loop_2_pr_U0->imageS_data_V_din(blendOpt83_Loop_2_pr_U0_imageS_data_V_din);
    blendOpt83_Loop_2_pr_U0->imageS_data_V_full_n(imageS_data_V_full_n);
    blendOpt83_Loop_2_pr_U0->imageS_data_V_write(blendOpt83_Loop_2_pr_U0_imageS_data_V_write);
    imageA_rows_load3_lo_2_U = new fifo_w10_d2_A("imageA_rows_load3_lo_2_U");
    imageA_rows_load3_lo_2_U->clk(ap_clk);
    imageA_rows_load3_lo_2_U->reset(ap_rst);
    imageA_rows_load3_lo_2_U->if_read_ce(ap_var_for_const0);
    imageA_rows_load3_lo_2_U->if_write_ce(ap_var_for_const0);
    imageA_rows_load3_lo_2_U->if_din(blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_din);
    imageA_rows_load3_lo_2_U->if_full_n(imageA_rows_load3_lo_2_full_n);
    imageA_rows_load3_lo_2_U->if_write(blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_write);
    imageA_rows_load3_lo_2_U->if_dout(imageA_rows_load3_lo_2_dout);
    imageA_rows_load3_lo_2_U->if_empty_n(imageA_rows_load3_lo_2_empty_n);
    imageA_rows_load3_lo_2_U->if_read(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_read);
    imageA_cols_load4_lo_2_U = new fifo_w11_d2_A("imageA_cols_load4_lo_2_U");
    imageA_cols_load4_lo_2_U->clk(ap_clk);
    imageA_cols_load4_lo_2_U->reset(ap_rst);
    imageA_cols_load4_lo_2_U->if_read_ce(ap_var_for_const0);
    imageA_cols_load4_lo_2_U->if_write_ce(ap_var_for_const0);
    imageA_cols_load4_lo_2_U->if_din(blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_din);
    imageA_cols_load4_lo_2_U->if_full_n(imageA_cols_load4_lo_2_full_n);
    imageA_cols_load4_lo_2_U->if_write(blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_write);
    imageA_cols_load4_lo_2_U->if_dout(imageA_cols_load4_lo_2_dout);
    imageA_cols_load4_lo_2_U->if_empty_n(imageA_cols_load4_lo_2_empty_n);
    imageA_cols_load4_lo_2_U->if_read(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_read);
    p_imageA_in_V_V_U = new fifo_w8_d2_A("p_imageA_in_V_V_U");
    p_imageA_in_V_V_U->clk(ap_clk);
    p_imageA_in_V_V_U->reset(ap_rst);
    p_imageA_in_V_V_U->if_read_ce(ap_var_for_const0);
    p_imageA_in_V_V_U->if_write_ce(ap_var_for_const0);
    p_imageA_in_V_V_U->if_din(blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_din);
    p_imageA_in_V_V_U->if_full_n(p_imageA_in_V_V_full_n);
    p_imageA_in_V_V_U->if_write(blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_write);
    p_imageA_in_V_V_U->if_dout(p_imageA_in_V_V_dout);
    p_imageA_in_V_V_U->if_empty_n(p_imageA_in_V_V_empty_n);
    p_imageA_in_V_V_U->if_read(xFPyrDownGaussianBlu_U0_p_imageA_in_V_V_read);
    p_imageB_in_V_V_U = new fifo_w8_d2_A("p_imageB_in_V_V_U");
    p_imageB_in_V_V_U->clk(ap_clk);
    p_imageB_in_V_V_U->reset(ap_rst);
    p_imageB_in_V_V_U->if_read_ce(ap_var_for_const0);
    p_imageB_in_V_V_U->if_write_ce(ap_var_for_const0);
    p_imageB_in_V_V_U->if_din(blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_din);
    p_imageB_in_V_V_U->if_full_n(p_imageB_in_V_V_full_n);
    p_imageB_in_V_V_U->if_write(blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_write);
    p_imageB_in_V_V_U->if_dout(p_imageB_in_V_V_dout);
    p_imageB_in_V_V_U->if_empty_n(p_imageB_in_V_V_empty_n);
    p_imageB_in_V_V_U->if_read(xFPyrDownGaussianBlu_U0_p_imageB_in_V_V_read);
    imageA_rows_load3_lo_1_U = new fifo_w10_d2_A("imageA_rows_load3_lo_1_U");
    imageA_rows_load3_lo_1_U->clk(ap_clk);
    imageA_rows_load3_lo_1_U->reset(ap_rst);
    imageA_rows_load3_lo_1_U->if_read_ce(ap_var_for_const0);
    imageA_rows_load3_lo_1_U->if_write_ce(ap_var_for_const0);
    imageA_rows_load3_lo_1_U->if_din(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_din);
    imageA_rows_load3_lo_1_U->if_full_n(imageA_rows_load3_lo_1_full_n);
    imageA_rows_load3_lo_1_U->if_write(blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_write);
    imageA_rows_load3_lo_1_U->if_dout(imageA_rows_load3_lo_1_dout);
    imageA_rows_load3_lo_1_U->if_empty_n(imageA_rows_load3_lo_1_empty_n);
    imageA_rows_load3_lo_1_U->if_read(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_read);
    imageA_cols_load4_lo_1_U = new fifo_w11_d2_A("imageA_cols_load4_lo_1_U");
    imageA_cols_load4_lo_1_U->clk(ap_clk);
    imageA_cols_load4_lo_1_U->reset(ap_rst);
    imageA_cols_load4_lo_1_U->if_read_ce(ap_var_for_const0);
    imageA_cols_load4_lo_1_U->if_write_ce(ap_var_for_const0);
    imageA_cols_load4_lo_1_U->if_din(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_din);
    imageA_cols_load4_lo_1_U->if_full_n(imageA_cols_load4_lo_1_full_n);
    imageA_cols_load4_lo_1_U->if_write(blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_write);
    imageA_cols_load4_lo_1_U->if_dout(imageA_cols_load4_lo_1_dout);
    imageA_cols_load4_lo_1_U->if_empty_n(imageA_cols_load4_lo_1_empty_n);
    imageA_cols_load4_lo_1_U->if_read(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_read);
    p_imageS_out_V_V_U = new fifo_w8_d2_A("p_imageS_out_V_V_U");
    p_imageS_out_V_V_U->clk(ap_clk);
    p_imageS_out_V_V_U->reset(ap_rst);
    p_imageS_out_V_V_U->if_read_ce(ap_var_for_const0);
    p_imageS_out_V_V_U->if_write_ce(ap_var_for_const0);
    p_imageS_out_V_V_U->if_din(xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_din);
    p_imageS_out_V_V_U->if_full_n(p_imageS_out_V_V_full_n);
    p_imageS_out_V_V_U->if_write(xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_write);
    p_imageS_out_V_V_U->if_dout(p_imageS_out_V_V_dout);
    p_imageS_out_V_V_U->if_empty_n(p_imageS_out_V_V_empty_n);
    p_imageS_out_V_V_U->if_read(blendOpt83_Loop_2_pr_U0_p_imageS_out_V_V_read);
    imageA_rows_load3_lo_U = new fifo_w10_d2_A("imageA_rows_load3_lo_U");
    imageA_rows_load3_lo_U->clk(ap_clk);
    imageA_rows_load3_lo_U->reset(ap_rst);
    imageA_rows_load3_lo_U->if_read_ce(ap_var_for_const0);
    imageA_rows_load3_lo_U->if_write_ce(ap_var_for_const0);
    imageA_rows_load3_lo_U->if_din(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_din);
    imageA_rows_load3_lo_U->if_full_n(imageA_rows_load3_lo_full_n);
    imageA_rows_load3_lo_U->if_write(xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_write);
    imageA_rows_load3_lo_U->if_dout(imageA_rows_load3_lo_dout);
    imageA_rows_load3_lo_U->if_empty_n(imageA_rows_load3_lo_empty_n);
    imageA_rows_load3_lo_U->if_read(blendOpt83_Loop_2_pr_U0_imageA_rows_load3_loc_read);
    imageA_cols_load4_lo_U = new fifo_w11_d2_A("imageA_cols_load4_lo_U");
    imageA_cols_load4_lo_U->clk(ap_clk);
    imageA_cols_load4_lo_U->reset(ap_rst);
    imageA_cols_load4_lo_U->if_read_ce(ap_var_for_const0);
    imageA_cols_load4_lo_U->if_write_ce(ap_var_for_const0);
    imageA_cols_load4_lo_U->if_din(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_din);
    imageA_cols_load4_lo_U->if_full_n(imageA_cols_load4_lo_full_n);
    imageA_cols_load4_lo_U->if_write(xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_write);
    imageA_cols_load4_lo_U->if_dout(imageA_cols_load4_lo_dout);
    imageA_cols_load4_lo_U->if_empty_n(imageA_cols_load4_lo_empty_n);
    imageA_cols_load4_lo_U->if_read(blendOpt83_Loop_2_pr_U0_imageA_cols_load4_loc_read);
    start_for_xFPyrDoDeQ_U = new start_for_xFPyrDoDeQ("start_for_xFPyrDoDeQ_U");
    start_for_xFPyrDoDeQ_U->clk(ap_clk);
    start_for_xFPyrDoDeQ_U->reset(ap_rst);
    start_for_xFPyrDoDeQ_U->if_read_ce(ap_var_for_const0);
    start_for_xFPyrDoDeQ_U->if_write_ce(ap_var_for_const0);
    start_for_xFPyrDoDeQ_U->if_din(start_for_xFPyrDownGaussianBlu_U0_din);
    start_for_xFPyrDoDeQ_U->if_full_n(start_for_xFPyrDownGaussianBlu_U0_full_n);
    start_for_xFPyrDoDeQ_U->if_write(blendOpt83_Loop_1_pr_U0_start_write);
    start_for_xFPyrDoDeQ_U->if_dout(start_for_xFPyrDownGaussianBlu_U0_dout);
    start_for_xFPyrDoDeQ_U->if_empty_n(start_for_xFPyrDownGaussianBlu_U0_empty_n);
    start_for_xFPyrDoDeQ_U->if_read(xFPyrDownGaussianBlu_U0_ap_ready);
    start_for_blendOpEe0_U = new start_for_blendOpEe0("start_for_blendOpEe0_U");
    start_for_blendOpEe0_U->clk(ap_clk);
    start_for_blendOpEe0_U->reset(ap_rst);
    start_for_blendOpEe0_U->if_read_ce(ap_var_for_const0);
    start_for_blendOpEe0_U->if_write_ce(ap_var_for_const0);
    start_for_blendOpEe0_U->if_din(start_for_blendOpt83_Loop_2_pr_U0_din);
    start_for_blendOpEe0_U->if_full_n(start_for_blendOpt83_Loop_2_pr_U0_full_n);
    start_for_blendOpEe0_U->if_write(xFPyrDownGaussianBlu_U0_start_write);
    start_for_blendOpEe0_U->if_dout(start_for_blendOpt83_Loop_2_pr_U0_dout);
    start_for_blendOpEe0_U->if_empty_n(start_for_blendOpt83_Loop_2_pr_U0_empty_n);
    start_for_blendOpEe0_U->if_read(blendOpt83_Loop_2_pr_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( blendOpt83_Loop_2_pr_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( blendOpt83_Block_pr_U0_ap_idle );
    sensitive << ( blendOpt83_Loop_1_pr_U0_ap_idle );
    sensitive << ( xFPyrDownGaussianBlu_U0_ap_idle );
    sensitive << ( blendOpt83_Loop_2_pr_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_sync_blendOpt83_Block_pr_U0_ap_ready);
    sensitive << ( blendOpt83_Block_pr_U0_ap_ready );
    sensitive << ( ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready );

    SC_METHOD(thread_ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready);
    sensitive << ( blendOpt83_Loop_1_pr_U0_ap_ready );
    sensitive << ( ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( blendOpt83_Loop_2_pr_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_blendOpt83_Block_pr_U0_ap_ready );
    sensitive << ( ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready );

    SC_METHOD(thread_blendOpt83_Block_pr_U0_ap_continue);

    SC_METHOD(thread_blendOpt83_Block_pr_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready );

    SC_METHOD(thread_blendOpt83_Block_pr_U0_start_full_n);

    SC_METHOD(thread_blendOpt83_Block_pr_U0_start_write);

    SC_METHOD(thread_blendOpt83_Loop_1_pr_U0_ap_continue);

    SC_METHOD(thread_blendOpt83_Loop_1_pr_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready );

    SC_METHOD(thread_blendOpt83_Loop_2_pr_U0_ap_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_blendOpt83_Loop_2_pr_U0_ap_start);
    sensitive << ( start_for_blendOpt83_Loop_2_pr_U0_empty_n );

    SC_METHOD(thread_blendOpt83_Loop_2_pr_U0_start_full_n);

    SC_METHOD(thread_blendOpt83_Loop_2_pr_U0_start_write);

    SC_METHOD(thread_imageA_cols_read);
    sensitive << ( blendOpt83_Block_pr_U0_imageA_cols_read );

    SC_METHOD(thread_imageA_data_V_read);
    sensitive << ( blendOpt83_Loop_1_pr_U0_imageA_data_V_read );

    SC_METHOD(thread_imageA_rows_read);
    sensitive << ( blendOpt83_Block_pr_U0_imageA_rows_read );

    SC_METHOD(thread_imageB_data_V_read);
    sensitive << ( blendOpt83_Loop_1_pr_U0_imageB_data_V_read );

    SC_METHOD(thread_imageS_data_V_din);
    sensitive << ( blendOpt83_Loop_2_pr_U0_imageS_data_V_din );

    SC_METHOD(thread_imageS_data_V_write);
    sensitive << ( blendOpt83_Loop_2_pr_U0_imageS_data_V_write );

    SC_METHOD(thread_start_for_blendOpt83_Loop_2_pr_U0_din);

    SC_METHOD(thread_start_for_xFPyrDownGaussianBlu_U0_din);

    SC_METHOD(thread_xFPyrDownGaussianBlu_U0_ap_continue);

    SC_METHOD(thread_xFPyrDownGaussianBlu_U0_ap_start);
    sensitive << ( start_for_xFPyrDownGaussianBlu_U0_empty_n );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready = SC_LOGIC_0;
    blendOpt83_Block_pr_U0_ap_ready_count = "00";
    ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready = SC_LOGIC_0;
    blendOpt83_Loop_1_pr_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blendOpt_480_640_83_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, imageA_rows_dout, "(port)imageA_rows_dout");
    sc_trace(mVcdFile, imageA_rows_empty_n, "(port)imageA_rows_empty_n");
    sc_trace(mVcdFile, imageA_rows_read, "(port)imageA_rows_read");
    sc_trace(mVcdFile, imageA_cols_dout, "(port)imageA_cols_dout");
    sc_trace(mVcdFile, imageA_cols_empty_n, "(port)imageA_cols_empty_n");
    sc_trace(mVcdFile, imageA_cols_read, "(port)imageA_cols_read");
    sc_trace(mVcdFile, imageA_data_V_dout, "(port)imageA_data_V_dout");
    sc_trace(mVcdFile, imageA_data_V_empty_n, "(port)imageA_data_V_empty_n");
    sc_trace(mVcdFile, imageA_data_V_read, "(port)imageA_data_V_read");
    sc_trace(mVcdFile, imageB_data_V_dout, "(port)imageB_data_V_dout");
    sc_trace(mVcdFile, imageB_data_V_empty_n, "(port)imageB_data_V_empty_n");
    sc_trace(mVcdFile, imageB_data_V_read, "(port)imageB_data_V_read");
    sc_trace(mVcdFile, imageS_data_V_din, "(port)imageS_data_V_din");
    sc_trace(mVcdFile, imageS_data_V_full_n, "(port)imageS_data_V_full_n");
    sc_trace(mVcdFile, imageS_data_V_write, "(port)imageS_data_V_write");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_start, "blendOpt83_Block_pr_U0_ap_start");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_done, "blendOpt83_Block_pr_U0_ap_done");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_continue, "blendOpt83_Block_pr_U0_ap_continue");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_idle, "blendOpt83_Block_pr_U0_ap_idle");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_ready, "blendOpt83_Block_pr_U0_ap_ready");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_rows_read, "blendOpt83_Block_pr_U0_imageA_rows_read");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_cols_read, "blendOpt83_Block_pr_U0_imageA_cols_read");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_din, "blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_din");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_write, "blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_write");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_din, "blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_din");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_write, "blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_write");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_start, "blendOpt83_Loop_1_pr_U0_ap_start");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_done, "blendOpt83_Loop_1_pr_U0_ap_done");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_continue, "blendOpt83_Loop_1_pr_U0_ap_continue");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_idle, "blendOpt83_Loop_1_pr_U0_ap_idle");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_ready, "blendOpt83_Loop_1_pr_U0_ap_ready");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_start_out, "blendOpt83_Loop_1_pr_U0_start_out");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_start_write, "blendOpt83_Loop_1_pr_U0_start_write");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_read, "blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_read");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_read, "blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_read");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_data_V_read, "blendOpt83_Loop_1_pr_U0_imageA_data_V_read");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_din, "blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_din");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_write, "blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_write");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageB_data_V_read, "blendOpt83_Loop_1_pr_U0_imageB_data_V_read");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_din, "blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_din");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_write, "blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_write");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_din, "blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_din");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_write, "blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_write");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_din, "blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_din");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_write, "blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_write");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_ap_start, "xFPyrDownGaussianBlu_U0_ap_start");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_ap_done, "xFPyrDownGaussianBlu_U0_ap_done");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_ap_continue, "xFPyrDownGaussianBlu_U0_ap_continue");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_ap_idle, "xFPyrDownGaussianBlu_U0_ap_idle");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_ap_ready, "xFPyrDownGaussianBlu_U0_ap_ready");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_start_out, "xFPyrDownGaussianBlu_U0_start_out");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_start_write, "xFPyrDownGaussianBlu_U0_start_write");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_p_imageA_in_V_V_read, "xFPyrDownGaussianBlu_U0_p_imageA_in_V_V_read");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_p_imageB_in_V_V_read, "xFPyrDownGaussianBlu_U0_p_imageB_in_V_V_read");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_din, "xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_din");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_write, "xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_write");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_read, "xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_read");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_read, "xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_read");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_din, "xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_din");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_write, "xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_write");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_din, "xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_din");
    sc_trace(mVcdFile, xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_write, "xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_write");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_ap_start, "blendOpt83_Loop_2_pr_U0_ap_start");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_ap_done, "blendOpt83_Loop_2_pr_U0_ap_done");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_ap_continue, "blendOpt83_Loop_2_pr_U0_ap_continue");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_ap_idle, "blendOpt83_Loop_2_pr_U0_ap_idle");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_ap_ready, "blendOpt83_Loop_2_pr_U0_ap_ready");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_imageA_rows_load3_loc_read, "blendOpt83_Loop_2_pr_U0_imageA_rows_load3_loc_read");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_imageA_cols_load4_loc_read, "blendOpt83_Loop_2_pr_U0_imageA_cols_load4_loc_read");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_p_imageS_out_V_V_read, "blendOpt83_Loop_2_pr_U0_p_imageS_out_V_V_read");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_imageS_data_V_din, "blendOpt83_Loop_2_pr_U0_imageS_data_V_din");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_imageS_data_V_write, "blendOpt83_Loop_2_pr_U0_imageS_data_V_write");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, imageA_rows_load3_lo_2_full_n, "imageA_rows_load3_lo_2_full_n");
    sc_trace(mVcdFile, imageA_rows_load3_lo_2_dout, "imageA_rows_load3_lo_2_dout");
    sc_trace(mVcdFile, imageA_rows_load3_lo_2_empty_n, "imageA_rows_load3_lo_2_empty_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_2_full_n, "imageA_cols_load4_lo_2_full_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_2_dout, "imageA_cols_load4_lo_2_dout");
    sc_trace(mVcdFile, imageA_cols_load4_lo_2_empty_n, "imageA_cols_load4_lo_2_empty_n");
    sc_trace(mVcdFile, p_imageA_in_V_V_full_n, "p_imageA_in_V_V_full_n");
    sc_trace(mVcdFile, p_imageA_in_V_V_dout, "p_imageA_in_V_V_dout");
    sc_trace(mVcdFile, p_imageA_in_V_V_empty_n, "p_imageA_in_V_V_empty_n");
    sc_trace(mVcdFile, p_imageB_in_V_V_full_n, "p_imageB_in_V_V_full_n");
    sc_trace(mVcdFile, p_imageB_in_V_V_dout, "p_imageB_in_V_V_dout");
    sc_trace(mVcdFile, p_imageB_in_V_V_empty_n, "p_imageB_in_V_V_empty_n");
    sc_trace(mVcdFile, imageA_rows_load3_lo_1_full_n, "imageA_rows_load3_lo_1_full_n");
    sc_trace(mVcdFile, imageA_rows_load3_lo_1_dout, "imageA_rows_load3_lo_1_dout");
    sc_trace(mVcdFile, imageA_rows_load3_lo_1_empty_n, "imageA_rows_load3_lo_1_empty_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_1_full_n, "imageA_cols_load4_lo_1_full_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_1_dout, "imageA_cols_load4_lo_1_dout");
    sc_trace(mVcdFile, imageA_cols_load4_lo_1_empty_n, "imageA_cols_load4_lo_1_empty_n");
    sc_trace(mVcdFile, p_imageS_out_V_V_full_n, "p_imageS_out_V_V_full_n");
    sc_trace(mVcdFile, p_imageS_out_V_V_dout, "p_imageS_out_V_V_dout");
    sc_trace(mVcdFile, p_imageS_out_V_V_empty_n, "p_imageS_out_V_V_empty_n");
    sc_trace(mVcdFile, imageA_rows_load3_lo_full_n, "imageA_rows_load3_lo_full_n");
    sc_trace(mVcdFile, imageA_rows_load3_lo_dout, "imageA_rows_load3_lo_dout");
    sc_trace(mVcdFile, imageA_rows_load3_lo_empty_n, "imageA_rows_load3_lo_empty_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_full_n, "imageA_cols_load4_lo_full_n");
    sc_trace(mVcdFile, imageA_cols_load4_lo_dout, "imageA_cols_load4_lo_dout");
    sc_trace(mVcdFile, imageA_cols_load4_lo_empty_n, "imageA_cols_load4_lo_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready, "ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_blendOpt83_Block_pr_U0_ap_ready, "ap_sync_blendOpt83_Block_pr_U0_ap_ready");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_ap_ready_count, "blendOpt83_Block_pr_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready, "ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready, "ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready");
    sc_trace(mVcdFile, blendOpt83_Loop_1_pr_U0_ap_ready_count, "blendOpt83_Loop_1_pr_U0_ap_ready_count");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_start_full_n, "blendOpt83_Block_pr_U0_start_full_n");
    sc_trace(mVcdFile, blendOpt83_Block_pr_U0_start_write, "blendOpt83_Block_pr_U0_start_write");
    sc_trace(mVcdFile, start_for_xFPyrDownGaussianBlu_U0_din, "start_for_xFPyrDownGaussianBlu_U0_din");
    sc_trace(mVcdFile, start_for_xFPyrDownGaussianBlu_U0_full_n, "start_for_xFPyrDownGaussianBlu_U0_full_n");
    sc_trace(mVcdFile, start_for_xFPyrDownGaussianBlu_U0_dout, "start_for_xFPyrDownGaussianBlu_U0_dout");
    sc_trace(mVcdFile, start_for_xFPyrDownGaussianBlu_U0_empty_n, "start_for_xFPyrDownGaussianBlu_U0_empty_n");
    sc_trace(mVcdFile, start_for_blendOpt83_Loop_2_pr_U0_din, "start_for_blendOpt83_Loop_2_pr_U0_din");
    sc_trace(mVcdFile, start_for_blendOpt83_Loop_2_pr_U0_full_n, "start_for_blendOpt83_Loop_2_pr_U0_full_n");
    sc_trace(mVcdFile, start_for_blendOpt83_Loop_2_pr_U0_dout, "start_for_blendOpt83_Loop_2_pr_U0_dout");
    sc_trace(mVcdFile, start_for_blendOpt83_Loop_2_pr_U0_empty_n, "start_for_blendOpt83_Loop_2_pr_U0_empty_n");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_start_full_n, "blendOpt83_Loop_2_pr_U0_start_full_n");
    sc_trace(mVcdFile, blendOpt83_Loop_2_pr_U0_start_write, "blendOpt83_Loop_2_pr_U0_start_write");
#endif

    }
}

blendOpt_480_640_83::~blendOpt_480_640_83() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete blendOpt83_Block_pr_U0;
    delete blendOpt83_Loop_1_pr_U0;
    delete xFPyrDownGaussianBlu_U0;
    delete blendOpt83_Loop_2_pr_U0;
    delete imageA_rows_load3_lo_2_U;
    delete imageA_cols_load4_lo_2_U;
    delete p_imageA_in_V_V_U;
    delete p_imageB_in_V_V_U;
    delete imageA_rows_load3_lo_1_U;
    delete imageA_cols_load4_lo_1_U;
    delete p_imageS_out_V_V_U;
    delete imageA_rows_load3_lo_U;
    delete imageA_cols_load4_lo_U;
    delete start_for_xFPyrDoDeQ_U;
    delete start_for_blendOpEe0_U;
}

void blendOpt_480_640_83::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready = ap_sync_blendOpt83_Block_pr_U0_ap_ready.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready = ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_0, blendOpt83_Block_pr_U0_ap_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        blendOpt83_Block_pr_U0_ap_ready_count = (!blendOpt83_Block_pr_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(blendOpt83_Block_pr_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(blendOpt83_Block_pr_U0_ap_ready.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        blendOpt83_Block_pr_U0_ap_ready_count = (!blendOpt83_Block_pr_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(blendOpt83_Block_pr_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, blendOpt83_Loop_1_pr_U0_ap_ready.read()))) {
        blendOpt83_Loop_1_pr_U0_ap_ready_count = (!blendOpt83_Loop_1_pr_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(blendOpt83_Loop_1_pr_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, blendOpt83_Loop_1_pr_U0_ap_ready.read()))) {
        blendOpt83_Loop_1_pr_U0_ap_ready_count = (!blendOpt83_Loop_1_pr_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(blendOpt83_Loop_1_pr_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
}

void blendOpt_480_640_83::thread_ap_done() {
    ap_done = blendOpt83_Loop_2_pr_U0_ap_done.read();
}

void blendOpt_480_640_83::thread_ap_idle() {
    ap_idle = (blendOpt83_Block_pr_U0_ap_idle.read() & blendOpt83_Loop_1_pr_U0_ap_idle.read() & xFPyrDownGaussianBlu_U0_ap_idle.read() & blendOpt83_Loop_2_pr_U0_ap_idle.read());
}

void blendOpt_480_640_83::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void blendOpt_480_640_83::thread_ap_sync_blendOpt83_Block_pr_U0_ap_ready() {
    ap_sync_blendOpt83_Block_pr_U0_ap_ready = (blendOpt83_Block_pr_U0_ap_ready.read() | ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready.read());
}

void blendOpt_480_640_83::thread_ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready() {
    ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready = (blendOpt83_Loop_1_pr_U0_ap_ready.read() | ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready.read());
}

void blendOpt_480_640_83::thread_ap_sync_continue() {
    ap_sync_continue = ap_continue.read();
}

void blendOpt_480_640_83::thread_ap_sync_done() {
    ap_sync_done = blendOpt83_Loop_2_pr_U0_ap_done.read();
}

void blendOpt_480_640_83::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_blendOpt83_Block_pr_U0_ap_ready.read() & ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready.read());
}

void blendOpt_480_640_83::thread_blendOpt83_Block_pr_U0_ap_continue() {
    blendOpt83_Block_pr_U0_ap_continue = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_blendOpt83_Block_pr_U0_ap_start() {
    blendOpt83_Block_pr_U0_ap_start = (ap_start.read() & (ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendOpt_480_640_83::thread_blendOpt83_Block_pr_U0_start_full_n() {
    blendOpt83_Block_pr_U0_start_full_n = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_blendOpt83_Block_pr_U0_start_write() {
    blendOpt83_Block_pr_U0_start_write = ap_const_logic_0;
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_1_pr_U0_ap_continue() {
    blendOpt83_Loop_1_pr_U0_ap_continue = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_1_pr_U0_ap_start() {
    blendOpt83_Loop_1_pr_U0_ap_start = (ap_start.read() & (ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_2_pr_U0_ap_continue() {
    blendOpt83_Loop_2_pr_U0_ap_continue = ap_continue.read();
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_2_pr_U0_ap_start() {
    blendOpt83_Loop_2_pr_U0_ap_start = start_for_blendOpt83_Loop_2_pr_U0_empty_n.read();
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_2_pr_U0_start_full_n() {
    blendOpt83_Loop_2_pr_U0_start_full_n = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_blendOpt83_Loop_2_pr_U0_start_write() {
    blendOpt83_Loop_2_pr_U0_start_write = ap_const_logic_0;
}

void blendOpt_480_640_83::thread_imageA_cols_read() {
    imageA_cols_read = blendOpt83_Block_pr_U0_imageA_cols_read.read();
}

void blendOpt_480_640_83::thread_imageA_data_V_read() {
    imageA_data_V_read = blendOpt83_Loop_1_pr_U0_imageA_data_V_read.read();
}

void blendOpt_480_640_83::thread_imageA_rows_read() {
    imageA_rows_read = blendOpt83_Block_pr_U0_imageA_rows_read.read();
}

void blendOpt_480_640_83::thread_imageB_data_V_read() {
    imageB_data_V_read = blendOpt83_Loop_1_pr_U0_imageB_data_V_read.read();
}

void blendOpt_480_640_83::thread_imageS_data_V_din() {
    imageS_data_V_din = blendOpt83_Loop_2_pr_U0_imageS_data_V_din.read();
}

void blendOpt_480_640_83::thread_imageS_data_V_write() {
    imageS_data_V_write = blendOpt83_Loop_2_pr_U0_imageS_data_V_write.read();
}

void blendOpt_480_640_83::thread_start_for_blendOpt83_Loop_2_pr_U0_din() {
    start_for_blendOpt83_Loop_2_pr_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void blendOpt_480_640_83::thread_start_for_xFPyrDownGaussianBlu_U0_din() {
    start_for_xFPyrDownGaussianBlu_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void blendOpt_480_640_83::thread_xFPyrDownGaussianBlu_U0_ap_continue() {
    xFPyrDownGaussianBlu_U0_ap_continue = ap_const_logic_1;
}

void blendOpt_480_640_83::thread_xFPyrDownGaussianBlu_U0_ap_start() {
    xFPyrDownGaussianBlu_U0_ap_start = start_for_xFPyrDownGaussianBlu_U0_empty_n.read();
}

}

