// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "blendTop.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<8> blendTop::ap_const_lv8_0 = "00000000";
const sc_lv<1> blendTop::ap_const_lv1_0 = "0";
const sc_logic blendTop::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic blendTop::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> blendTop::ap_const_lv2_0 = "00";
const sc_lv<2> blendTop::ap_const_lv2_1 = "1";
const bool blendTop::ap_const_boolean_1 = true;

blendTop::blendTop(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->start_full_n(start_for_blendL_U0_full_n);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->start_out(Block_proc_U0_start_out);
    Block_proc_U0->start_write(Block_proc_U0_start_write);
    Block_proc_U0->pyrLA0_rows_out_din(Block_proc_U0_pyrLA0_rows_out_din);
    Block_proc_U0->pyrLA0_rows_out_full_n(pyrLA0_rows_c_full_n);
    Block_proc_U0->pyrLA0_rows_out_write(Block_proc_U0_pyrLA0_rows_out_write);
    Block_proc_U0->pyrLA0_cols_out_din(Block_proc_U0_pyrLA0_cols_out_din);
    Block_proc_U0->pyrLA0_cols_out_full_n(pyrLA0_cols_c_full_n);
    Block_proc_U0->pyrLA0_cols_out_write(Block_proc_U0_pyrLA0_cols_out_write);
    Block_proc_U0->pyrLA1_rows_out_din(Block_proc_U0_pyrLA1_rows_out_din);
    Block_proc_U0->pyrLA1_rows_out_full_n(pyrLA1_rows_c_full_n);
    Block_proc_U0->pyrLA1_rows_out_write(Block_proc_U0_pyrLA1_rows_out_write);
    Block_proc_U0->pyrLA1_rows_out1_din(Block_proc_U0_pyrLA1_rows_out1_din);
    Block_proc_U0->pyrLA1_rows_out1_full_n(pyrLA1_rows_c4_full_n);
    Block_proc_U0->pyrLA1_rows_out1_write(Block_proc_U0_pyrLA1_rows_out1_write);
    Block_proc_U0->pyrLA1_cols_out_din(Block_proc_U0_pyrLA1_cols_out_din);
    Block_proc_U0->pyrLA1_cols_out_full_n(pyrLA1_cols_c_full_n);
    Block_proc_U0->pyrLA1_cols_out_write(Block_proc_U0_pyrLA1_cols_out_write);
    Block_proc_U0->pyrLA1_cols_out2_din(Block_proc_U0_pyrLA1_cols_out2_din);
    Block_proc_U0->pyrLA1_cols_out2_full_n(pyrLA1_cols_c5_full_n);
    Block_proc_U0->pyrLA1_cols_out2_write(Block_proc_U0_pyrLA1_cols_out2_write);
    AXIvideo2xfMat84_U0 = new AXIvideo2xfMat84("AXIvideo2xfMat84_U0");
    AXIvideo2xfMat84_U0->ap_clk(ap_clk);
    AXIvideo2xfMat84_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2xfMat84_U0->ap_start(AXIvideo2xfMat84_U0_ap_start);
    AXIvideo2xfMat84_U0->ap_done(AXIvideo2xfMat84_U0_ap_done);
    AXIvideo2xfMat84_U0->ap_continue(AXIvideo2xfMat84_U0_ap_continue);
    AXIvideo2xfMat84_U0->ap_idle(AXIvideo2xfMat84_U0_ap_idle);
    AXIvideo2xfMat84_U0->ap_ready(AXIvideo2xfMat84_U0_ap_ready);
    AXIvideo2xfMat84_U0->p_pyrLA0_TDATA(p_pyrLA0_TDATA);
    AXIvideo2xfMat84_U0->p_pyrLA0_TVALID(p_pyrLA0_TVALID);
    AXIvideo2xfMat84_U0->p_pyrLA0_TREADY(AXIvideo2xfMat84_U0_p_pyrLA0_TREADY);
    AXIvideo2xfMat84_U0->p_pyrLA0_TKEEP(p_pyrLA0_TKEEP);
    AXIvideo2xfMat84_U0->p_pyrLA0_TSTRB(p_pyrLA0_TSTRB);
    AXIvideo2xfMat84_U0->p_pyrLA0_TUSER(p_pyrLA0_TUSER);
    AXIvideo2xfMat84_U0->p_pyrLA0_TLAST(p_pyrLA0_TLAST);
    AXIvideo2xfMat84_U0->p_pyrLA0_TID(p_pyrLA0_TID);
    AXIvideo2xfMat84_U0->p_pyrLA0_TDEST(p_pyrLA0_TDEST);
    AXIvideo2xfMat84_U0->img_rows_dout(pyrLA0_rows_c_dout);
    AXIvideo2xfMat84_U0->img_rows_empty_n(pyrLA0_rows_c_empty_n);
    AXIvideo2xfMat84_U0->img_rows_read(AXIvideo2xfMat84_U0_img_rows_read);
    AXIvideo2xfMat84_U0->img_cols_dout(pyrLA0_cols_c_dout);
    AXIvideo2xfMat84_U0->img_cols_empty_n(pyrLA0_cols_c_empty_n);
    AXIvideo2xfMat84_U0->img_cols_read(AXIvideo2xfMat84_U0_img_cols_read);
    AXIvideo2xfMat84_U0->img_data_V_din(AXIvideo2xfMat84_U0_img_data_V_din);
    AXIvideo2xfMat84_U0->img_data_V_full_n(pyrLA0_data_V_full_n);
    AXIvideo2xfMat84_U0->img_data_V_write(AXIvideo2xfMat84_U0_img_data_V_write);
    AXIvideo2xfMat84_U0->img_rows_out_din(AXIvideo2xfMat84_U0_img_rows_out_din);
    AXIvideo2xfMat84_U0->img_rows_out_full_n(pyrLA0_rows_c6_full_n);
    AXIvideo2xfMat84_U0->img_rows_out_write(AXIvideo2xfMat84_U0_img_rows_out_write);
    AXIvideo2xfMat84_U0->img_cols_out_din(AXIvideo2xfMat84_U0_img_cols_out_din);
    AXIvideo2xfMat84_U0->img_cols_out_full_n(pyrLA0_cols_c7_full_n);
    AXIvideo2xfMat84_U0->img_cols_out_write(AXIvideo2xfMat84_U0_img_cols_out_write);
    AXIvideo2xfMat85_U0 = new AXIvideo2xfMat85("AXIvideo2xfMat85_U0");
    AXIvideo2xfMat85_U0->ap_clk(ap_clk);
    AXIvideo2xfMat85_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2xfMat85_U0->ap_start(AXIvideo2xfMat85_U0_ap_start);
    AXIvideo2xfMat85_U0->ap_done(AXIvideo2xfMat85_U0_ap_done);
    AXIvideo2xfMat85_U0->ap_continue(AXIvideo2xfMat85_U0_ap_continue);
    AXIvideo2xfMat85_U0->ap_idle(AXIvideo2xfMat85_U0_ap_idle);
    AXIvideo2xfMat85_U0->ap_ready(AXIvideo2xfMat85_U0_ap_ready);
    AXIvideo2xfMat85_U0->p_pyrLA1_TDATA(p_pyrLA1_TDATA);
    AXIvideo2xfMat85_U0->p_pyrLA1_TVALID(p_pyrLA1_TVALID);
    AXIvideo2xfMat85_U0->p_pyrLA1_TREADY(AXIvideo2xfMat85_U0_p_pyrLA1_TREADY);
    AXIvideo2xfMat85_U0->p_pyrLA1_TKEEP(p_pyrLA1_TKEEP);
    AXIvideo2xfMat85_U0->p_pyrLA1_TSTRB(p_pyrLA1_TSTRB);
    AXIvideo2xfMat85_U0->p_pyrLA1_TUSER(p_pyrLA1_TUSER);
    AXIvideo2xfMat85_U0->p_pyrLA1_TLAST(p_pyrLA1_TLAST);
    AXIvideo2xfMat85_U0->p_pyrLA1_TID(p_pyrLA1_TID);
    AXIvideo2xfMat85_U0->p_pyrLA1_TDEST(p_pyrLA1_TDEST);
    AXIvideo2xfMat85_U0->img_rows_dout(pyrLA1_rows_c_dout);
    AXIvideo2xfMat85_U0->img_rows_empty_n(pyrLA1_rows_c_empty_n);
    AXIvideo2xfMat85_U0->img_rows_read(AXIvideo2xfMat85_U0_img_rows_read);
    AXIvideo2xfMat85_U0->img_cols_dout(pyrLA1_cols_c_dout);
    AXIvideo2xfMat85_U0->img_cols_empty_n(pyrLA1_cols_c_empty_n);
    AXIvideo2xfMat85_U0->img_cols_read(AXIvideo2xfMat85_U0_img_cols_read);
    AXIvideo2xfMat85_U0->img_data_V_din(AXIvideo2xfMat85_U0_img_data_V_din);
    AXIvideo2xfMat85_U0->img_data_V_full_n(pyrLA1_data_V_full_n);
    AXIvideo2xfMat85_U0->img_data_V_write(AXIvideo2xfMat85_U0_img_data_V_write);
    AXIvideo2xfMat86_U0 = new AXIvideo2xfMat86("AXIvideo2xfMat86_U0");
    AXIvideo2xfMat86_U0->ap_clk(ap_clk);
    AXIvideo2xfMat86_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2xfMat86_U0->ap_start(AXIvideo2xfMat86_U0_ap_start);
    AXIvideo2xfMat86_U0->ap_done(AXIvideo2xfMat86_U0_ap_done);
    AXIvideo2xfMat86_U0->ap_continue(AXIvideo2xfMat86_U0_ap_continue);
    AXIvideo2xfMat86_U0->ap_idle(AXIvideo2xfMat86_U0_ap_idle);
    AXIvideo2xfMat86_U0->ap_ready(AXIvideo2xfMat86_U0_ap_ready);
    AXIvideo2xfMat86_U0->p_pyrLB0_TDATA(p_pyrLB0_TDATA);
    AXIvideo2xfMat86_U0->p_pyrLB0_TVALID(p_pyrLB0_TVALID);
    AXIvideo2xfMat86_U0->p_pyrLB0_TREADY(AXIvideo2xfMat86_U0_p_pyrLB0_TREADY);
    AXIvideo2xfMat86_U0->p_pyrLB0_TKEEP(p_pyrLB0_TKEEP);
    AXIvideo2xfMat86_U0->p_pyrLB0_TSTRB(p_pyrLB0_TSTRB);
    AXIvideo2xfMat86_U0->p_pyrLB0_TUSER(p_pyrLB0_TUSER);
    AXIvideo2xfMat86_U0->p_pyrLB0_TLAST(p_pyrLB0_TLAST);
    AXIvideo2xfMat86_U0->p_pyrLB0_TID(p_pyrLB0_TID);
    AXIvideo2xfMat86_U0->p_pyrLB0_TDEST(p_pyrLB0_TDEST);
    AXIvideo2xfMat86_U0->img_data_V_din(AXIvideo2xfMat86_U0_img_data_V_din);
    AXIvideo2xfMat86_U0->img_data_V_full_n(pyrLB0_data_V_full_n);
    AXIvideo2xfMat86_U0->img_data_V_write(AXIvideo2xfMat86_U0_img_data_V_write);
    AXIvideo2xfMat_U0 = new AXIvideo2xfMat("AXIvideo2xfMat_U0");
    AXIvideo2xfMat_U0->ap_clk(ap_clk);
    AXIvideo2xfMat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2xfMat_U0->ap_start(AXIvideo2xfMat_U0_ap_start);
    AXIvideo2xfMat_U0->ap_done(AXIvideo2xfMat_U0_ap_done);
    AXIvideo2xfMat_U0->ap_continue(AXIvideo2xfMat_U0_ap_continue);
    AXIvideo2xfMat_U0->ap_idle(AXIvideo2xfMat_U0_ap_idle);
    AXIvideo2xfMat_U0->ap_ready(AXIvideo2xfMat_U0_ap_ready);
    AXIvideo2xfMat_U0->p_pyrLB1_TDATA(p_pyrLB1_TDATA);
    AXIvideo2xfMat_U0->p_pyrLB1_TVALID(p_pyrLB1_TVALID);
    AXIvideo2xfMat_U0->p_pyrLB1_TREADY(AXIvideo2xfMat_U0_p_pyrLB1_TREADY);
    AXIvideo2xfMat_U0->p_pyrLB1_TKEEP(p_pyrLB1_TKEEP);
    AXIvideo2xfMat_U0->p_pyrLB1_TSTRB(p_pyrLB1_TSTRB);
    AXIvideo2xfMat_U0->p_pyrLB1_TUSER(p_pyrLB1_TUSER);
    AXIvideo2xfMat_U0->p_pyrLB1_TLAST(p_pyrLB1_TLAST);
    AXIvideo2xfMat_U0->p_pyrLB1_TID(p_pyrLB1_TID);
    AXIvideo2xfMat_U0->p_pyrLB1_TDEST(p_pyrLB1_TDEST);
    AXIvideo2xfMat_U0->img_data_V_din(AXIvideo2xfMat_U0_img_data_V_din);
    AXIvideo2xfMat_U0->img_data_V_full_n(pyrLB1_data_V_full_n);
    AXIvideo2xfMat_U0->img_data_V_write(AXIvideo2xfMat_U0_img_data_V_write);
    blendL_U0 = new blendL("blendL_U0");
    blendL_U0->ap_start(blendL_U0_ap_start);
    blendL_U0->start_full_n(blendL_U0_start_full_n);
    blendL_U0->start_out(blendL_U0_start_out);
    blendL_U0->start_write(blendL_U0_start_write);
    blendL_U0->pyrLA0_rows_dout(pyrLA0_rows_c6_dout);
    blendL_U0->pyrLA0_rows_empty_n(pyrLA0_rows_c6_empty_n);
    blendL_U0->pyrLA0_rows_read(blendL_U0_pyrLA0_rows_read);
    blendL_U0->pyrLA0_cols_dout(pyrLA0_cols_c7_dout);
    blendL_U0->pyrLA0_cols_empty_n(pyrLA0_cols_c7_empty_n);
    blendL_U0->pyrLA0_cols_read(blendL_U0_pyrLA0_cols_read);
    blendL_U0->pyrLA0_data_V_dout(pyrLA0_data_V_dout);
    blendL_U0->pyrLA0_data_V_empty_n(pyrLA0_data_V_empty_n);
    blendL_U0->pyrLA0_data_V_read(blendL_U0_pyrLA0_data_V_read);
    blendL_U0->pyrLA1_rows_dout(pyrLA1_rows_c4_dout);
    blendL_U0->pyrLA1_rows_empty_n(pyrLA1_rows_c4_empty_n);
    blendL_U0->pyrLA1_rows_read(blendL_U0_pyrLA1_rows_read);
    blendL_U0->pyrLA1_cols_dout(pyrLA1_cols_c5_dout);
    blendL_U0->pyrLA1_cols_empty_n(pyrLA1_cols_c5_empty_n);
    blendL_U0->pyrLA1_cols_read(blendL_U0_pyrLA1_cols_read);
    blendL_U0->pyrLA1_data_V_dout(pyrLA1_data_V_dout);
    blendL_U0->pyrLA1_data_V_empty_n(pyrLA1_data_V_empty_n);
    blendL_U0->pyrLA1_data_V_read(blendL_U0_pyrLA1_data_V_read);
    blendL_U0->pyrLB0_data_V_dout(pyrLB0_data_V_dout);
    blendL_U0->pyrLB0_data_V_empty_n(pyrLB0_data_V_empty_n);
    blendL_U0->pyrLB0_data_V_read(blendL_U0_pyrLB0_data_V_read);
    blendL_U0->pyrLB1_data_V_dout(pyrLB1_data_V_dout);
    blendL_U0->pyrLB1_data_V_empty_n(pyrLB1_data_V_empty_n);
    blendL_U0->pyrLB1_data_V_read(blendL_U0_pyrLB1_data_V_read);
    blendL_U0->pyrS0_data_V_din(blendL_U0_pyrS0_data_V_din);
    blendL_U0->pyrS0_data_V_full_n(pyrS0_data_V_full_n);
    blendL_U0->pyrS0_data_V_write(blendL_U0_pyrS0_data_V_write);
    blendL_U0->pyrS1_data_V_din(blendL_U0_pyrS1_data_V_din);
    blendL_U0->pyrS1_data_V_full_n(pyrS1_data_V_full_n);
    blendL_U0->pyrS1_data_V_write(blendL_U0_pyrS1_data_V_write);
    blendL_U0->ap_clk(ap_clk);
    blendL_U0->ap_rst(ap_rst_n_inv);
    blendL_U0->ap_done(blendL_U0_ap_done);
    blendL_U0->ap_ready(blendL_U0_ap_ready);
    blendL_U0->ap_idle(blendL_U0_ap_idle);
    blendL_U0->ap_continue(blendL_U0_ap_continue);
    xfMat2AXIvideo87_U0 = new xfMat2AXIvideo87("xfMat2AXIvideo87_U0");
    xfMat2AXIvideo87_U0->ap_clk(ap_clk);
    xfMat2AXIvideo87_U0->ap_rst(ap_rst_n_inv);
    xfMat2AXIvideo87_U0->ap_start(xfMat2AXIvideo87_U0_ap_start);
    xfMat2AXIvideo87_U0->ap_done(xfMat2AXIvideo87_U0_ap_done);
    xfMat2AXIvideo87_U0->ap_continue(xfMat2AXIvideo87_U0_ap_continue);
    xfMat2AXIvideo87_U0->ap_idle(xfMat2AXIvideo87_U0_ap_idle);
    xfMat2AXIvideo87_U0->ap_ready(xfMat2AXIvideo87_U0_ap_ready);
    xfMat2AXIvideo87_U0->img_data_V_dout(pyrS0_data_V_dout);
    xfMat2AXIvideo87_U0->img_data_V_empty_n(pyrS0_data_V_empty_n);
    xfMat2AXIvideo87_U0->img_data_V_read(xfMat2AXIvideo87_U0_img_data_V_read);
    xfMat2AXIvideo87_U0->p_pyrS0_TDATA(xfMat2AXIvideo87_U0_p_pyrS0_TDATA);
    xfMat2AXIvideo87_U0->p_pyrS0_TVALID(xfMat2AXIvideo87_U0_p_pyrS0_TVALID);
    xfMat2AXIvideo87_U0->p_pyrS0_TREADY(p_pyrS0_TREADY);
    xfMat2AXIvideo87_U0->p_pyrS0_TKEEP(xfMat2AXIvideo87_U0_p_pyrS0_TKEEP);
    xfMat2AXIvideo87_U0->p_pyrS0_TSTRB(xfMat2AXIvideo87_U0_p_pyrS0_TSTRB);
    xfMat2AXIvideo87_U0->p_pyrS0_TUSER(xfMat2AXIvideo87_U0_p_pyrS0_TUSER);
    xfMat2AXIvideo87_U0->p_pyrS0_TLAST(xfMat2AXIvideo87_U0_p_pyrS0_TLAST);
    xfMat2AXIvideo87_U0->p_pyrS0_TID(xfMat2AXIvideo87_U0_p_pyrS0_TID);
    xfMat2AXIvideo87_U0->p_pyrS0_TDEST(xfMat2AXIvideo87_U0_p_pyrS0_TDEST);
    xfMat2AXIvideo_U0 = new xfMat2AXIvideo("xfMat2AXIvideo_U0");
    xfMat2AXIvideo_U0->ap_clk(ap_clk);
    xfMat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    xfMat2AXIvideo_U0->ap_start(xfMat2AXIvideo_U0_ap_start);
    xfMat2AXIvideo_U0->ap_done(xfMat2AXIvideo_U0_ap_done);
    xfMat2AXIvideo_U0->ap_continue(xfMat2AXIvideo_U0_ap_continue);
    xfMat2AXIvideo_U0->ap_idle(xfMat2AXIvideo_U0_ap_idle);
    xfMat2AXIvideo_U0->ap_ready(xfMat2AXIvideo_U0_ap_ready);
    xfMat2AXIvideo_U0->img_data_V_dout(pyrS1_data_V_dout);
    xfMat2AXIvideo_U0->img_data_V_empty_n(pyrS1_data_V_empty_n);
    xfMat2AXIvideo_U0->img_data_V_read(xfMat2AXIvideo_U0_img_data_V_read);
    xfMat2AXIvideo_U0->p_pyrS1_TDATA(xfMat2AXIvideo_U0_p_pyrS1_TDATA);
    xfMat2AXIvideo_U0->p_pyrS1_TVALID(xfMat2AXIvideo_U0_p_pyrS1_TVALID);
    xfMat2AXIvideo_U0->p_pyrS1_TREADY(p_pyrS1_TREADY);
    xfMat2AXIvideo_U0->p_pyrS1_TKEEP(xfMat2AXIvideo_U0_p_pyrS1_TKEEP);
    xfMat2AXIvideo_U0->p_pyrS1_TSTRB(xfMat2AXIvideo_U0_p_pyrS1_TSTRB);
    xfMat2AXIvideo_U0->p_pyrS1_TUSER(xfMat2AXIvideo_U0_p_pyrS1_TUSER);
    xfMat2AXIvideo_U0->p_pyrS1_TLAST(xfMat2AXIvideo_U0_p_pyrS1_TLAST);
    xfMat2AXIvideo_U0->p_pyrS1_TID(xfMat2AXIvideo_U0_p_pyrS1_TID);
    xfMat2AXIvideo_U0->p_pyrS1_TDEST(xfMat2AXIvideo_U0_p_pyrS1_TDEST);
    pyrLA0_rows_c_U = new fifo_w10_d2_A_x1("pyrLA0_rows_c_U");
    pyrLA0_rows_c_U->clk(ap_clk);
    pyrLA0_rows_c_U->reset(ap_rst_n_inv);
    pyrLA0_rows_c_U->if_read_ce(ap_var_for_const0);
    pyrLA0_rows_c_U->if_write_ce(ap_var_for_const0);
    pyrLA0_rows_c_U->if_din(Block_proc_U0_pyrLA0_rows_out_din);
    pyrLA0_rows_c_U->if_full_n(pyrLA0_rows_c_full_n);
    pyrLA0_rows_c_U->if_write(Block_proc_U0_pyrLA0_rows_out_write);
    pyrLA0_rows_c_U->if_dout(pyrLA0_rows_c_dout);
    pyrLA0_rows_c_U->if_empty_n(pyrLA0_rows_c_empty_n);
    pyrLA0_rows_c_U->if_read(AXIvideo2xfMat84_U0_img_rows_read);
    pyrLA0_cols_c_U = new fifo_w11_d2_A_x0("pyrLA0_cols_c_U");
    pyrLA0_cols_c_U->clk(ap_clk);
    pyrLA0_cols_c_U->reset(ap_rst_n_inv);
    pyrLA0_cols_c_U->if_read_ce(ap_var_for_const0);
    pyrLA0_cols_c_U->if_write_ce(ap_var_for_const0);
    pyrLA0_cols_c_U->if_din(Block_proc_U0_pyrLA0_cols_out_din);
    pyrLA0_cols_c_U->if_full_n(pyrLA0_cols_c_full_n);
    pyrLA0_cols_c_U->if_write(Block_proc_U0_pyrLA0_cols_out_write);
    pyrLA0_cols_c_U->if_dout(pyrLA0_cols_c_dout);
    pyrLA0_cols_c_U->if_empty_n(pyrLA0_cols_c_empty_n);
    pyrLA0_cols_c_U->if_read(AXIvideo2xfMat84_U0_img_cols_read);
    pyrLA1_rows_c_U = new fifo_w9_d2_A_x0("pyrLA1_rows_c_U");
    pyrLA1_rows_c_U->clk(ap_clk);
    pyrLA1_rows_c_U->reset(ap_rst_n_inv);
    pyrLA1_rows_c_U->if_read_ce(ap_var_for_const0);
    pyrLA1_rows_c_U->if_write_ce(ap_var_for_const0);
    pyrLA1_rows_c_U->if_din(Block_proc_U0_pyrLA1_rows_out_din);
    pyrLA1_rows_c_U->if_full_n(pyrLA1_rows_c_full_n);
    pyrLA1_rows_c_U->if_write(Block_proc_U0_pyrLA1_rows_out_write);
    pyrLA1_rows_c_U->if_dout(pyrLA1_rows_c_dout);
    pyrLA1_rows_c_U->if_empty_n(pyrLA1_rows_c_empty_n);
    pyrLA1_rows_c_U->if_read(AXIvideo2xfMat85_U0_img_rows_read);
    pyrLA1_rows_c4_U = new fifo_w9_d3_A("pyrLA1_rows_c4_U");
    pyrLA1_rows_c4_U->clk(ap_clk);
    pyrLA1_rows_c4_U->reset(ap_rst_n_inv);
    pyrLA1_rows_c4_U->if_read_ce(ap_var_for_const0);
    pyrLA1_rows_c4_U->if_write_ce(ap_var_for_const0);
    pyrLA1_rows_c4_U->if_din(Block_proc_U0_pyrLA1_rows_out1_din);
    pyrLA1_rows_c4_U->if_full_n(pyrLA1_rows_c4_full_n);
    pyrLA1_rows_c4_U->if_write(Block_proc_U0_pyrLA1_rows_out1_write);
    pyrLA1_rows_c4_U->if_dout(pyrLA1_rows_c4_dout);
    pyrLA1_rows_c4_U->if_empty_n(pyrLA1_rows_c4_empty_n);
    pyrLA1_rows_c4_U->if_read(blendL_U0_pyrLA1_rows_read);
    pyrLA1_cols_c_U = new fifo_w10_d2_A_x1("pyrLA1_cols_c_U");
    pyrLA1_cols_c_U->clk(ap_clk);
    pyrLA1_cols_c_U->reset(ap_rst_n_inv);
    pyrLA1_cols_c_U->if_read_ce(ap_var_for_const0);
    pyrLA1_cols_c_U->if_write_ce(ap_var_for_const0);
    pyrLA1_cols_c_U->if_din(Block_proc_U0_pyrLA1_cols_out_din);
    pyrLA1_cols_c_U->if_full_n(pyrLA1_cols_c_full_n);
    pyrLA1_cols_c_U->if_write(Block_proc_U0_pyrLA1_cols_out_write);
    pyrLA1_cols_c_U->if_dout(pyrLA1_cols_c_dout);
    pyrLA1_cols_c_U->if_empty_n(pyrLA1_cols_c_empty_n);
    pyrLA1_cols_c_U->if_read(AXIvideo2xfMat85_U0_img_cols_read);
    pyrLA1_cols_c5_U = new fifo_w10_d3_A("pyrLA1_cols_c5_U");
    pyrLA1_cols_c5_U->clk(ap_clk);
    pyrLA1_cols_c5_U->reset(ap_rst_n_inv);
    pyrLA1_cols_c5_U->if_read_ce(ap_var_for_const0);
    pyrLA1_cols_c5_U->if_write_ce(ap_var_for_const0);
    pyrLA1_cols_c5_U->if_din(Block_proc_U0_pyrLA1_cols_out2_din);
    pyrLA1_cols_c5_U->if_full_n(pyrLA1_cols_c5_full_n);
    pyrLA1_cols_c5_U->if_write(Block_proc_U0_pyrLA1_cols_out2_write);
    pyrLA1_cols_c5_U->if_dout(pyrLA1_cols_c5_dout);
    pyrLA1_cols_c5_U->if_empty_n(pyrLA1_cols_c5_empty_n);
    pyrLA1_cols_c5_U->if_read(blendL_U0_pyrLA1_cols_read);
    pyrLA0_data_V_U = new fifo_w8_d1_A("pyrLA0_data_V_U");
    pyrLA0_data_V_U->clk(ap_clk);
    pyrLA0_data_V_U->reset(ap_rst_n_inv);
    pyrLA0_data_V_U->if_read_ce(ap_var_for_const0);
    pyrLA0_data_V_U->if_write_ce(ap_var_for_const0);
    pyrLA0_data_V_U->if_din(AXIvideo2xfMat84_U0_img_data_V_din);
    pyrLA0_data_V_U->if_full_n(pyrLA0_data_V_full_n);
    pyrLA0_data_V_U->if_write(AXIvideo2xfMat84_U0_img_data_V_write);
    pyrLA0_data_V_U->if_dout(pyrLA0_data_V_dout);
    pyrLA0_data_V_U->if_empty_n(pyrLA0_data_V_empty_n);
    pyrLA0_data_V_U->if_read(blendL_U0_pyrLA0_data_V_read);
    pyrLA0_rows_c6_U = new fifo_w10_d2_A_x1("pyrLA0_rows_c6_U");
    pyrLA0_rows_c6_U->clk(ap_clk);
    pyrLA0_rows_c6_U->reset(ap_rst_n_inv);
    pyrLA0_rows_c6_U->if_read_ce(ap_var_for_const0);
    pyrLA0_rows_c6_U->if_write_ce(ap_var_for_const0);
    pyrLA0_rows_c6_U->if_din(AXIvideo2xfMat84_U0_img_rows_out_din);
    pyrLA0_rows_c6_U->if_full_n(pyrLA0_rows_c6_full_n);
    pyrLA0_rows_c6_U->if_write(AXIvideo2xfMat84_U0_img_rows_out_write);
    pyrLA0_rows_c6_U->if_dout(pyrLA0_rows_c6_dout);
    pyrLA0_rows_c6_U->if_empty_n(pyrLA0_rows_c6_empty_n);
    pyrLA0_rows_c6_U->if_read(blendL_U0_pyrLA0_rows_read);
    pyrLA0_cols_c7_U = new fifo_w11_d2_A_x0("pyrLA0_cols_c7_U");
    pyrLA0_cols_c7_U->clk(ap_clk);
    pyrLA0_cols_c7_U->reset(ap_rst_n_inv);
    pyrLA0_cols_c7_U->if_read_ce(ap_var_for_const0);
    pyrLA0_cols_c7_U->if_write_ce(ap_var_for_const0);
    pyrLA0_cols_c7_U->if_din(AXIvideo2xfMat84_U0_img_cols_out_din);
    pyrLA0_cols_c7_U->if_full_n(pyrLA0_cols_c7_full_n);
    pyrLA0_cols_c7_U->if_write(AXIvideo2xfMat84_U0_img_cols_out_write);
    pyrLA0_cols_c7_U->if_dout(pyrLA0_cols_c7_dout);
    pyrLA0_cols_c7_U->if_empty_n(pyrLA0_cols_c7_empty_n);
    pyrLA0_cols_c7_U->if_read(blendL_U0_pyrLA0_cols_read);
    pyrLA1_data_V_U = new fifo_w8_d1_A("pyrLA1_data_V_U");
    pyrLA1_data_V_U->clk(ap_clk);
    pyrLA1_data_V_U->reset(ap_rst_n_inv);
    pyrLA1_data_V_U->if_read_ce(ap_var_for_const0);
    pyrLA1_data_V_U->if_write_ce(ap_var_for_const0);
    pyrLA1_data_V_U->if_din(AXIvideo2xfMat85_U0_img_data_V_din);
    pyrLA1_data_V_U->if_full_n(pyrLA1_data_V_full_n);
    pyrLA1_data_V_U->if_write(AXIvideo2xfMat85_U0_img_data_V_write);
    pyrLA1_data_V_U->if_dout(pyrLA1_data_V_dout);
    pyrLA1_data_V_U->if_empty_n(pyrLA1_data_V_empty_n);
    pyrLA1_data_V_U->if_read(blendL_U0_pyrLA1_data_V_read);
    pyrLB0_data_V_U = new fifo_w8_d1_A("pyrLB0_data_V_U");
    pyrLB0_data_V_U->clk(ap_clk);
    pyrLB0_data_V_U->reset(ap_rst_n_inv);
    pyrLB0_data_V_U->if_read_ce(ap_var_for_const0);
    pyrLB0_data_V_U->if_write_ce(ap_var_for_const0);
    pyrLB0_data_V_U->if_din(AXIvideo2xfMat86_U0_img_data_V_din);
    pyrLB0_data_V_U->if_full_n(pyrLB0_data_V_full_n);
    pyrLB0_data_V_U->if_write(AXIvideo2xfMat86_U0_img_data_V_write);
    pyrLB0_data_V_U->if_dout(pyrLB0_data_V_dout);
    pyrLB0_data_V_U->if_empty_n(pyrLB0_data_V_empty_n);
    pyrLB0_data_V_U->if_read(blendL_U0_pyrLB0_data_V_read);
    pyrLB1_data_V_U = new fifo_w8_d1_A("pyrLB1_data_V_U");
    pyrLB1_data_V_U->clk(ap_clk);
    pyrLB1_data_V_U->reset(ap_rst_n_inv);
    pyrLB1_data_V_U->if_read_ce(ap_var_for_const0);
    pyrLB1_data_V_U->if_write_ce(ap_var_for_const0);
    pyrLB1_data_V_U->if_din(AXIvideo2xfMat_U0_img_data_V_din);
    pyrLB1_data_V_U->if_full_n(pyrLB1_data_V_full_n);
    pyrLB1_data_V_U->if_write(AXIvideo2xfMat_U0_img_data_V_write);
    pyrLB1_data_V_U->if_dout(pyrLB1_data_V_dout);
    pyrLB1_data_V_U->if_empty_n(pyrLB1_data_V_empty_n);
    pyrLB1_data_V_U->if_read(blendL_U0_pyrLB1_data_V_read);
    pyrS0_data_V_U = new fifo_w8_d1_A("pyrS0_data_V_U");
    pyrS0_data_V_U->clk(ap_clk);
    pyrS0_data_V_U->reset(ap_rst_n_inv);
    pyrS0_data_V_U->if_read_ce(ap_var_for_const0);
    pyrS0_data_V_U->if_write_ce(ap_var_for_const0);
    pyrS0_data_V_U->if_din(blendL_U0_pyrS0_data_V_din);
    pyrS0_data_V_U->if_full_n(pyrS0_data_V_full_n);
    pyrS0_data_V_U->if_write(blendL_U0_pyrS0_data_V_write);
    pyrS0_data_V_U->if_dout(pyrS0_data_V_dout);
    pyrS0_data_V_U->if_empty_n(pyrS0_data_V_empty_n);
    pyrS0_data_V_U->if_read(xfMat2AXIvideo87_U0_img_data_V_read);
    pyrS1_data_V_U = new fifo_w8_d1_A("pyrS1_data_V_U");
    pyrS1_data_V_U->clk(ap_clk);
    pyrS1_data_V_U->reset(ap_rst_n_inv);
    pyrS1_data_V_U->if_read_ce(ap_var_for_const0);
    pyrS1_data_V_U->if_write_ce(ap_var_for_const0);
    pyrS1_data_V_U->if_din(blendL_U0_pyrS1_data_V_din);
    pyrS1_data_V_U->if_full_n(pyrS1_data_V_full_n);
    pyrS1_data_V_U->if_write(blendL_U0_pyrS1_data_V_write);
    pyrS1_data_V_U->if_dout(pyrS1_data_V_dout);
    pyrS1_data_V_U->if_empty_n(pyrS1_data_V_empty_n);
    pyrS1_data_V_U->if_read(xfMat2AXIvideo_U0_img_data_V_read);
    start_for_blendL_U0_U = new start_for_blendL_U0("start_for_blendL_U0_U");
    start_for_blendL_U0_U->clk(ap_clk);
    start_for_blendL_U0_U->reset(ap_rst_n_inv);
    start_for_blendL_U0_U->if_read_ce(ap_var_for_const0);
    start_for_blendL_U0_U->if_write_ce(ap_var_for_const0);
    start_for_blendL_U0_U->if_din(start_for_blendL_U0_din);
    start_for_blendL_U0_U->if_full_n(start_for_blendL_U0_full_n);
    start_for_blendL_U0_U->if_write(Block_proc_U0_start_write);
    start_for_blendL_U0_U->if_dout(start_for_blendL_U0_dout);
    start_for_blendL_U0_U->if_empty_n(start_for_blendL_U0_empty_n);
    start_for_blendL_U0_U->if_read(blendL_U0_ap_ready);
    start_for_xfMat2AIfE_U = new start_for_xfMat2AIfE("start_for_xfMat2AIfE_U");
    start_for_xfMat2AIfE_U->clk(ap_clk);
    start_for_xfMat2AIfE_U->reset(ap_rst_n_inv);
    start_for_xfMat2AIfE_U->if_read_ce(ap_var_for_const0);
    start_for_xfMat2AIfE_U->if_write_ce(ap_var_for_const0);
    start_for_xfMat2AIfE_U->if_din(start_for_xfMat2AXIvideo87_U0_din);
    start_for_xfMat2AIfE_U->if_full_n(start_for_xfMat2AXIvideo87_U0_full_n);
    start_for_xfMat2AIfE_U->if_write(blendL_U0_start_write);
    start_for_xfMat2AIfE_U->if_dout(start_for_xfMat2AXIvideo87_U0_dout);
    start_for_xfMat2AIfE_U->if_empty_n(start_for_xfMat2AXIvideo87_U0_empty_n);
    start_for_xfMat2AIfE_U->if_read(xfMat2AXIvideo87_U0_ap_ready);
    start_for_xfMat2AJfO_U = new start_for_xfMat2AJfO("start_for_xfMat2AJfO_U");
    start_for_xfMat2AJfO_U->clk(ap_clk);
    start_for_xfMat2AJfO_U->reset(ap_rst_n_inv);
    start_for_xfMat2AJfO_U->if_read_ce(ap_var_for_const0);
    start_for_xfMat2AJfO_U->if_write_ce(ap_var_for_const0);
    start_for_xfMat2AJfO_U->if_din(start_for_xfMat2AXIvideo_U0_din);
    start_for_xfMat2AJfO_U->if_full_n(start_for_xfMat2AXIvideo_U0_full_n);
    start_for_xfMat2AJfO_U->if_write(blendL_U0_start_write);
    start_for_xfMat2AJfO_U->if_dout(start_for_xfMat2AXIvideo_U0_dout);
    start_for_xfMat2AJfO_U->if_empty_n(start_for_xfMat2AXIvideo_U0_empty_n);
    start_for_xfMat2AJfO_U->if_read(xfMat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXIvideo2xfMat84_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2xfMat84_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready );

    SC_METHOD(thread_AXIvideo2xfMat84_U0_start_full_n);

    SC_METHOD(thread_AXIvideo2xfMat84_U0_start_write);

    SC_METHOD(thread_AXIvideo2xfMat85_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2xfMat85_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready );

    SC_METHOD(thread_AXIvideo2xfMat85_U0_start_full_n);

    SC_METHOD(thread_AXIvideo2xfMat85_U0_start_write);

    SC_METHOD(thread_AXIvideo2xfMat86_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2xfMat86_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready );

    SC_METHOD(thread_AXIvideo2xfMat86_U0_start_full_n);

    SC_METHOD(thread_AXIvideo2xfMat86_U0_start_write);

    SC_METHOD(thread_AXIvideo2xfMat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2xfMat_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat_U0_ap_ready );

    SC_METHOD(thread_AXIvideo2xfMat_U0_start_full_n);

    SC_METHOD(thread_AXIvideo2xfMat_U0_start_write);

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_proc_U0_ap_idle );
    sensitive << ( AXIvideo2xfMat84_U0_ap_idle );
    sensitive << ( AXIvideo2xfMat85_U0_ap_idle );
    sensitive << ( AXIvideo2xfMat86_U0_ap_idle );
    sensitive << ( AXIvideo2xfMat_U0_ap_idle );
    sensitive << ( blendL_U0_ap_idle );
    sensitive << ( xfMat2AXIvideo87_U0_ap_idle );
    sensitive << ( xfMat2AXIvideo_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_AXIvideo2xfMat84_U0_ap_ready);
    sensitive << ( AXIvideo2xfMat84_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready );

    SC_METHOD(thread_ap_sync_AXIvideo2xfMat85_U0_ap_ready);
    sensitive << ( AXIvideo2xfMat85_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready );

    SC_METHOD(thread_ap_sync_AXIvideo2xfMat86_U0_ap_ready);
    sensitive << ( AXIvideo2xfMat86_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready );

    SC_METHOD(thread_ap_sync_AXIvideo2xfMat_U0_ap_ready);
    sensitive << ( AXIvideo2xfMat_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2xfMat_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Block_proc_U0_ap_ready);
    sensitive << ( Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( xfMat2AXIvideo87_U0_ap_done );
    sensitive << ( xfMat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2xfMat84_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2xfMat85_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2xfMat86_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2xfMat_U0_ap_ready );

    SC_METHOD(thread_blendL_U0_ap_continue);

    SC_METHOD(thread_blendL_U0_ap_start);
    sensitive << ( start_for_blendL_U0_empty_n );

    SC_METHOD(thread_blendL_U0_start_full_n);
    sensitive << ( start_for_xfMat2AXIvideo87_U0_full_n );
    sensitive << ( start_for_xfMat2AXIvideo_U0_full_n );

    SC_METHOD(thread_p_pyrLA0_TREADY);
    sensitive << ( AXIvideo2xfMat84_U0_p_pyrLA0_TREADY );

    SC_METHOD(thread_p_pyrLA1_TREADY);
    sensitive << ( AXIvideo2xfMat85_U0_p_pyrLA1_TREADY );

    SC_METHOD(thread_p_pyrLB0_TREADY);
    sensitive << ( AXIvideo2xfMat86_U0_p_pyrLB0_TREADY );

    SC_METHOD(thread_p_pyrLB1_TREADY);
    sensitive << ( AXIvideo2xfMat_U0_p_pyrLB1_TREADY );

    SC_METHOD(thread_p_pyrS0_TDATA);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TDATA );

    SC_METHOD(thread_p_pyrS0_TDEST);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TDEST );

    SC_METHOD(thread_p_pyrS0_TID);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TID );

    SC_METHOD(thread_p_pyrS0_TKEEP);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TKEEP );

    SC_METHOD(thread_p_pyrS0_TLAST);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TLAST );

    SC_METHOD(thread_p_pyrS0_TSTRB);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TSTRB );

    SC_METHOD(thread_p_pyrS0_TUSER);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TUSER );

    SC_METHOD(thread_p_pyrS0_TVALID);
    sensitive << ( xfMat2AXIvideo87_U0_p_pyrS0_TVALID );

    SC_METHOD(thread_p_pyrS1_TDATA);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TDATA );

    SC_METHOD(thread_p_pyrS1_TDEST);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TDEST );

    SC_METHOD(thread_p_pyrS1_TID);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TID );

    SC_METHOD(thread_p_pyrS1_TKEEP);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TKEEP );

    SC_METHOD(thread_p_pyrS1_TLAST);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TLAST );

    SC_METHOD(thread_p_pyrS1_TSTRB);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TSTRB );

    SC_METHOD(thread_p_pyrS1_TUSER);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TUSER );

    SC_METHOD(thread_p_pyrS1_TVALID);
    sensitive << ( xfMat2AXIvideo_U0_p_pyrS1_TVALID );

    SC_METHOD(thread_start_for_blendL_U0_din);

    SC_METHOD(thread_start_for_xfMat2AXIvideo87_U0_din);

    SC_METHOD(thread_start_for_xfMat2AXIvideo_U0_din);

    SC_METHOD(thread_xfMat2AXIvideo87_U0_ap_continue);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_xfMat2AXIvideo87_U0_ap_start);
    sensitive << ( start_for_xfMat2AXIvideo87_U0_empty_n );

    SC_METHOD(thread_xfMat2AXIvideo87_U0_start_full_n);

    SC_METHOD(thread_xfMat2AXIvideo87_U0_start_write);

    SC_METHOD(thread_xfMat2AXIvideo_U0_ap_continue);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_xfMat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_xfMat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_xfMat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_xfMat2AXIvideo_U0_start_write);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_proc_U0_ap_ready = SC_LOGIC_0;
    Block_proc_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2xfMat84_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2xfMat85_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2xfMat86_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2xfMat_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2xfMat_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blendTop_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, p_pyrLA0_TDATA, "(port)p_pyrLA0_TDATA");
    sc_trace(mVcdFile, p_pyrLA0_TKEEP, "(port)p_pyrLA0_TKEEP");
    sc_trace(mVcdFile, p_pyrLA0_TSTRB, "(port)p_pyrLA0_TSTRB");
    sc_trace(mVcdFile, p_pyrLA0_TUSER, "(port)p_pyrLA0_TUSER");
    sc_trace(mVcdFile, p_pyrLA0_TLAST, "(port)p_pyrLA0_TLAST");
    sc_trace(mVcdFile, p_pyrLA0_TID, "(port)p_pyrLA0_TID");
    sc_trace(mVcdFile, p_pyrLA0_TDEST, "(port)p_pyrLA0_TDEST");
    sc_trace(mVcdFile, p_pyrLA1_TDATA, "(port)p_pyrLA1_TDATA");
    sc_trace(mVcdFile, p_pyrLA1_TKEEP, "(port)p_pyrLA1_TKEEP");
    sc_trace(mVcdFile, p_pyrLA1_TSTRB, "(port)p_pyrLA1_TSTRB");
    sc_trace(mVcdFile, p_pyrLA1_TUSER, "(port)p_pyrLA1_TUSER");
    sc_trace(mVcdFile, p_pyrLA1_TLAST, "(port)p_pyrLA1_TLAST");
    sc_trace(mVcdFile, p_pyrLA1_TID, "(port)p_pyrLA1_TID");
    sc_trace(mVcdFile, p_pyrLA1_TDEST, "(port)p_pyrLA1_TDEST");
    sc_trace(mVcdFile, p_pyrLB0_TDATA, "(port)p_pyrLB0_TDATA");
    sc_trace(mVcdFile, p_pyrLB0_TKEEP, "(port)p_pyrLB0_TKEEP");
    sc_trace(mVcdFile, p_pyrLB0_TSTRB, "(port)p_pyrLB0_TSTRB");
    sc_trace(mVcdFile, p_pyrLB0_TUSER, "(port)p_pyrLB0_TUSER");
    sc_trace(mVcdFile, p_pyrLB0_TLAST, "(port)p_pyrLB0_TLAST");
    sc_trace(mVcdFile, p_pyrLB0_TID, "(port)p_pyrLB0_TID");
    sc_trace(mVcdFile, p_pyrLB0_TDEST, "(port)p_pyrLB0_TDEST");
    sc_trace(mVcdFile, p_pyrLB1_TDATA, "(port)p_pyrLB1_TDATA");
    sc_trace(mVcdFile, p_pyrLB1_TKEEP, "(port)p_pyrLB1_TKEEP");
    sc_trace(mVcdFile, p_pyrLB1_TSTRB, "(port)p_pyrLB1_TSTRB");
    sc_trace(mVcdFile, p_pyrLB1_TUSER, "(port)p_pyrLB1_TUSER");
    sc_trace(mVcdFile, p_pyrLB1_TLAST, "(port)p_pyrLB1_TLAST");
    sc_trace(mVcdFile, p_pyrLB1_TID, "(port)p_pyrLB1_TID");
    sc_trace(mVcdFile, p_pyrLB1_TDEST, "(port)p_pyrLB1_TDEST");
    sc_trace(mVcdFile, p_pyrS0_TDATA, "(port)p_pyrS0_TDATA");
    sc_trace(mVcdFile, p_pyrS0_TKEEP, "(port)p_pyrS0_TKEEP");
    sc_trace(mVcdFile, p_pyrS0_TSTRB, "(port)p_pyrS0_TSTRB");
    sc_trace(mVcdFile, p_pyrS0_TUSER, "(port)p_pyrS0_TUSER");
    sc_trace(mVcdFile, p_pyrS0_TLAST, "(port)p_pyrS0_TLAST");
    sc_trace(mVcdFile, p_pyrS0_TID, "(port)p_pyrS0_TID");
    sc_trace(mVcdFile, p_pyrS0_TDEST, "(port)p_pyrS0_TDEST");
    sc_trace(mVcdFile, p_pyrS1_TDATA, "(port)p_pyrS1_TDATA");
    sc_trace(mVcdFile, p_pyrS1_TKEEP, "(port)p_pyrS1_TKEEP");
    sc_trace(mVcdFile, p_pyrS1_TSTRB, "(port)p_pyrS1_TSTRB");
    sc_trace(mVcdFile, p_pyrS1_TUSER, "(port)p_pyrS1_TUSER");
    sc_trace(mVcdFile, p_pyrS1_TLAST, "(port)p_pyrS1_TLAST");
    sc_trace(mVcdFile, p_pyrS1_TID, "(port)p_pyrS1_TID");
    sc_trace(mVcdFile, p_pyrS1_TDEST, "(port)p_pyrS1_TDEST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, p_pyrLA0_TVALID, "(port)p_pyrLA0_TVALID");
    sc_trace(mVcdFile, p_pyrLA0_TREADY, "(port)p_pyrLA0_TREADY");
    sc_trace(mVcdFile, p_pyrLA1_TVALID, "(port)p_pyrLA1_TVALID");
    sc_trace(mVcdFile, p_pyrLA1_TREADY, "(port)p_pyrLA1_TREADY");
    sc_trace(mVcdFile, p_pyrLB0_TVALID, "(port)p_pyrLB0_TVALID");
    sc_trace(mVcdFile, p_pyrLB0_TREADY, "(port)p_pyrLB0_TREADY");
    sc_trace(mVcdFile, p_pyrLB1_TVALID, "(port)p_pyrLB1_TVALID");
    sc_trace(mVcdFile, p_pyrLB1_TREADY, "(port)p_pyrLB1_TREADY");
    sc_trace(mVcdFile, p_pyrS0_TVALID, "(port)p_pyrS0_TVALID");
    sc_trace(mVcdFile, p_pyrS0_TREADY, "(port)p_pyrS0_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, p_pyrS1_TVALID, "(port)p_pyrS1_TVALID");
    sc_trace(mVcdFile, p_pyrS1_TREADY, "(port)p_pyrS1_TREADY");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_start_out, "Block_proc_U0_start_out");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA0_rows_out_din, "Block_proc_U0_pyrLA0_rows_out_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA0_rows_out_write, "Block_proc_U0_pyrLA0_rows_out_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA0_cols_out_din, "Block_proc_U0_pyrLA0_cols_out_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA0_cols_out_write, "Block_proc_U0_pyrLA0_cols_out_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_rows_out_din, "Block_proc_U0_pyrLA1_rows_out_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_rows_out_write, "Block_proc_U0_pyrLA1_rows_out_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_rows_out1_din, "Block_proc_U0_pyrLA1_rows_out1_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_rows_out1_write, "Block_proc_U0_pyrLA1_rows_out1_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_cols_out_din, "Block_proc_U0_pyrLA1_cols_out_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_cols_out_write, "Block_proc_U0_pyrLA1_cols_out_write");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_cols_out2_din, "Block_proc_U0_pyrLA1_cols_out2_din");
    sc_trace(mVcdFile, Block_proc_U0_pyrLA1_cols_out2_write, "Block_proc_U0_pyrLA1_cols_out2_write");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_start, "AXIvideo2xfMat84_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_done, "AXIvideo2xfMat84_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_continue, "AXIvideo2xfMat84_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_idle, "AXIvideo2xfMat84_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_ready, "AXIvideo2xfMat84_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_p_pyrLA0_TREADY, "AXIvideo2xfMat84_U0_p_pyrLA0_TREADY");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_rows_read, "AXIvideo2xfMat84_U0_img_rows_read");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_cols_read, "AXIvideo2xfMat84_U0_img_cols_read");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_data_V_din, "AXIvideo2xfMat84_U0_img_data_V_din");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_data_V_write, "AXIvideo2xfMat84_U0_img_data_V_write");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_rows_out_din, "AXIvideo2xfMat84_U0_img_rows_out_din");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_rows_out_write, "AXIvideo2xfMat84_U0_img_rows_out_write");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_cols_out_din, "AXIvideo2xfMat84_U0_img_cols_out_din");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_img_cols_out_write, "AXIvideo2xfMat84_U0_img_cols_out_write");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_start, "AXIvideo2xfMat85_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_done, "AXIvideo2xfMat85_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_continue, "AXIvideo2xfMat85_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_idle, "AXIvideo2xfMat85_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_ready, "AXIvideo2xfMat85_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_p_pyrLA1_TREADY, "AXIvideo2xfMat85_U0_p_pyrLA1_TREADY");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_img_rows_read, "AXIvideo2xfMat85_U0_img_rows_read");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_img_cols_read, "AXIvideo2xfMat85_U0_img_cols_read");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_img_data_V_din, "AXIvideo2xfMat85_U0_img_data_V_din");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_img_data_V_write, "AXIvideo2xfMat85_U0_img_data_V_write");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_start, "AXIvideo2xfMat86_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_done, "AXIvideo2xfMat86_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_continue, "AXIvideo2xfMat86_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_idle, "AXIvideo2xfMat86_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_ready, "AXIvideo2xfMat86_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_p_pyrLB0_TREADY, "AXIvideo2xfMat86_U0_p_pyrLB0_TREADY");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_img_data_V_din, "AXIvideo2xfMat86_U0_img_data_V_din");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_img_data_V_write, "AXIvideo2xfMat86_U0_img_data_V_write");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_start, "AXIvideo2xfMat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_done, "AXIvideo2xfMat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_continue, "AXIvideo2xfMat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_idle, "AXIvideo2xfMat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_ready, "AXIvideo2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_p_pyrLB1_TREADY, "AXIvideo2xfMat_U0_p_pyrLB1_TREADY");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_img_data_V_din, "AXIvideo2xfMat_U0_img_data_V_din");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_img_data_V_write, "AXIvideo2xfMat_U0_img_data_V_write");
    sc_trace(mVcdFile, blendL_U0_ap_start, "blendL_U0_ap_start");
    sc_trace(mVcdFile, blendL_U0_start_full_n, "blendL_U0_start_full_n");
    sc_trace(mVcdFile, blendL_U0_start_out, "blendL_U0_start_out");
    sc_trace(mVcdFile, blendL_U0_start_write, "blendL_U0_start_write");
    sc_trace(mVcdFile, blendL_U0_pyrLA0_rows_read, "blendL_U0_pyrLA0_rows_read");
    sc_trace(mVcdFile, blendL_U0_pyrLA0_cols_read, "blendL_U0_pyrLA0_cols_read");
    sc_trace(mVcdFile, blendL_U0_pyrLA0_data_V_read, "blendL_U0_pyrLA0_data_V_read");
    sc_trace(mVcdFile, blendL_U0_pyrLA1_rows_read, "blendL_U0_pyrLA1_rows_read");
    sc_trace(mVcdFile, blendL_U0_pyrLA1_cols_read, "blendL_U0_pyrLA1_cols_read");
    sc_trace(mVcdFile, blendL_U0_pyrLA1_data_V_read, "blendL_U0_pyrLA1_data_V_read");
    sc_trace(mVcdFile, blendL_U0_pyrLB0_data_V_read, "blendL_U0_pyrLB0_data_V_read");
    sc_trace(mVcdFile, blendL_U0_pyrLB1_data_V_read, "blendL_U0_pyrLB1_data_V_read");
    sc_trace(mVcdFile, blendL_U0_pyrS0_data_V_din, "blendL_U0_pyrS0_data_V_din");
    sc_trace(mVcdFile, blendL_U0_pyrS0_data_V_write, "blendL_U0_pyrS0_data_V_write");
    sc_trace(mVcdFile, blendL_U0_pyrS1_data_V_din, "blendL_U0_pyrS1_data_V_din");
    sc_trace(mVcdFile, blendL_U0_pyrS1_data_V_write, "blendL_U0_pyrS1_data_V_write");
    sc_trace(mVcdFile, blendL_U0_ap_done, "blendL_U0_ap_done");
    sc_trace(mVcdFile, blendL_U0_ap_ready, "blendL_U0_ap_ready");
    sc_trace(mVcdFile, blendL_U0_ap_idle, "blendL_U0_ap_idle");
    sc_trace(mVcdFile, blendL_U0_ap_continue, "blendL_U0_ap_continue");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_ap_start, "xfMat2AXIvideo87_U0_ap_start");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_ap_done, "xfMat2AXIvideo87_U0_ap_done");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_ap_continue, "xfMat2AXIvideo87_U0_ap_continue");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_ap_idle, "xfMat2AXIvideo87_U0_ap_idle");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_ap_ready, "xfMat2AXIvideo87_U0_ap_ready");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_img_data_V_read, "xfMat2AXIvideo87_U0_img_data_V_read");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TDATA, "xfMat2AXIvideo87_U0_p_pyrS0_TDATA");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TVALID, "xfMat2AXIvideo87_U0_p_pyrS0_TVALID");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TKEEP, "xfMat2AXIvideo87_U0_p_pyrS0_TKEEP");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TSTRB, "xfMat2AXIvideo87_U0_p_pyrS0_TSTRB");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TUSER, "xfMat2AXIvideo87_U0_p_pyrS0_TUSER");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TLAST, "xfMat2AXIvideo87_U0_p_pyrS0_TLAST");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TID, "xfMat2AXIvideo87_U0_p_pyrS0_TID");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_p_pyrS0_TDEST, "xfMat2AXIvideo87_U0_p_pyrS0_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_ap_start, "xfMat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_ap_done, "xfMat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_ap_continue, "xfMat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_ap_idle, "xfMat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_ap_ready, "xfMat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_img_data_V_read, "xfMat2AXIvideo_U0_img_data_V_read");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TDATA, "xfMat2AXIvideo_U0_p_pyrS1_TDATA");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TVALID, "xfMat2AXIvideo_U0_p_pyrS1_TVALID");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TKEEP, "xfMat2AXIvideo_U0_p_pyrS1_TKEEP");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TSTRB, "xfMat2AXIvideo_U0_p_pyrS1_TSTRB");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TUSER, "xfMat2AXIvideo_U0_p_pyrS1_TUSER");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TLAST, "xfMat2AXIvideo_U0_p_pyrS1_TLAST");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TID, "xfMat2AXIvideo_U0_p_pyrS1_TID");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_p_pyrS1_TDEST, "xfMat2AXIvideo_U0_p_pyrS1_TDEST");
    sc_trace(mVcdFile, pyrLA0_rows_c_full_n, "pyrLA0_rows_c_full_n");
    sc_trace(mVcdFile, pyrLA0_rows_c_dout, "pyrLA0_rows_c_dout");
    sc_trace(mVcdFile, pyrLA0_rows_c_empty_n, "pyrLA0_rows_c_empty_n");
    sc_trace(mVcdFile, pyrLA0_cols_c_full_n, "pyrLA0_cols_c_full_n");
    sc_trace(mVcdFile, pyrLA0_cols_c_dout, "pyrLA0_cols_c_dout");
    sc_trace(mVcdFile, pyrLA0_cols_c_empty_n, "pyrLA0_cols_c_empty_n");
    sc_trace(mVcdFile, pyrLA1_rows_c_full_n, "pyrLA1_rows_c_full_n");
    sc_trace(mVcdFile, pyrLA1_rows_c_dout, "pyrLA1_rows_c_dout");
    sc_trace(mVcdFile, pyrLA1_rows_c_empty_n, "pyrLA1_rows_c_empty_n");
    sc_trace(mVcdFile, pyrLA1_rows_c4_full_n, "pyrLA1_rows_c4_full_n");
    sc_trace(mVcdFile, pyrLA1_rows_c4_dout, "pyrLA1_rows_c4_dout");
    sc_trace(mVcdFile, pyrLA1_rows_c4_empty_n, "pyrLA1_rows_c4_empty_n");
    sc_trace(mVcdFile, pyrLA1_cols_c_full_n, "pyrLA1_cols_c_full_n");
    sc_trace(mVcdFile, pyrLA1_cols_c_dout, "pyrLA1_cols_c_dout");
    sc_trace(mVcdFile, pyrLA1_cols_c_empty_n, "pyrLA1_cols_c_empty_n");
    sc_trace(mVcdFile, pyrLA1_cols_c5_full_n, "pyrLA1_cols_c5_full_n");
    sc_trace(mVcdFile, pyrLA1_cols_c5_dout, "pyrLA1_cols_c5_dout");
    sc_trace(mVcdFile, pyrLA1_cols_c5_empty_n, "pyrLA1_cols_c5_empty_n");
    sc_trace(mVcdFile, pyrLA0_data_V_full_n, "pyrLA0_data_V_full_n");
    sc_trace(mVcdFile, pyrLA0_data_V_dout, "pyrLA0_data_V_dout");
    sc_trace(mVcdFile, pyrLA0_data_V_empty_n, "pyrLA0_data_V_empty_n");
    sc_trace(mVcdFile, pyrLA0_rows_c6_full_n, "pyrLA0_rows_c6_full_n");
    sc_trace(mVcdFile, pyrLA0_rows_c6_dout, "pyrLA0_rows_c6_dout");
    sc_trace(mVcdFile, pyrLA0_rows_c6_empty_n, "pyrLA0_rows_c6_empty_n");
    sc_trace(mVcdFile, pyrLA0_cols_c7_full_n, "pyrLA0_cols_c7_full_n");
    sc_trace(mVcdFile, pyrLA0_cols_c7_dout, "pyrLA0_cols_c7_dout");
    sc_trace(mVcdFile, pyrLA0_cols_c7_empty_n, "pyrLA0_cols_c7_empty_n");
    sc_trace(mVcdFile, pyrLA1_data_V_full_n, "pyrLA1_data_V_full_n");
    sc_trace(mVcdFile, pyrLA1_data_V_dout, "pyrLA1_data_V_dout");
    sc_trace(mVcdFile, pyrLA1_data_V_empty_n, "pyrLA1_data_V_empty_n");
    sc_trace(mVcdFile, pyrLB0_data_V_full_n, "pyrLB0_data_V_full_n");
    sc_trace(mVcdFile, pyrLB0_data_V_dout, "pyrLB0_data_V_dout");
    sc_trace(mVcdFile, pyrLB0_data_V_empty_n, "pyrLB0_data_V_empty_n");
    sc_trace(mVcdFile, pyrLB1_data_V_full_n, "pyrLB1_data_V_full_n");
    sc_trace(mVcdFile, pyrLB1_data_V_dout, "pyrLB1_data_V_dout");
    sc_trace(mVcdFile, pyrLB1_data_V_empty_n, "pyrLB1_data_V_empty_n");
    sc_trace(mVcdFile, pyrS0_data_V_full_n, "pyrS0_data_V_full_n");
    sc_trace(mVcdFile, pyrS0_data_V_dout, "pyrS0_data_V_dout");
    sc_trace(mVcdFile, pyrS0_data_V_empty_n, "pyrS0_data_V_empty_n");
    sc_trace(mVcdFile, pyrS1_data_V_full_n, "pyrS1_data_V_full_n");
    sc_trace(mVcdFile, pyrS1_data_V_dout, "pyrS1_data_V_dout");
    sc_trace(mVcdFile, pyrS1_data_V_empty_n, "pyrS1_data_V_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_proc_U0_ap_ready, "ap_sync_reg_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_proc_U0_ap_ready, "ap_sync_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready_count, "Block_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready, "ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2xfMat84_U0_ap_ready, "ap_sync_AXIvideo2xfMat84_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_ap_ready_count, "AXIvideo2xfMat84_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready, "ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2xfMat85_U0_ap_ready, "ap_sync_AXIvideo2xfMat85_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_ap_ready_count, "AXIvideo2xfMat85_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready, "ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2xfMat86_U0_ap_ready, "ap_sync_AXIvideo2xfMat86_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_ap_ready_count, "AXIvideo2xfMat86_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2xfMat_U0_ap_ready, "ap_sync_reg_AXIvideo2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2xfMat_U0_ap_ready, "ap_sync_AXIvideo2xfMat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_ap_ready_count, "AXIvideo2xfMat_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_blendL_U0_din, "start_for_blendL_U0_din");
    sc_trace(mVcdFile, start_for_blendL_U0_full_n, "start_for_blendL_U0_full_n");
    sc_trace(mVcdFile, start_for_blendL_U0_dout, "start_for_blendL_U0_dout");
    sc_trace(mVcdFile, start_for_blendL_U0_empty_n, "start_for_blendL_U0_empty_n");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_start_full_n, "AXIvideo2xfMat84_U0_start_full_n");
    sc_trace(mVcdFile, AXIvideo2xfMat84_U0_start_write, "AXIvideo2xfMat84_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_start_full_n, "AXIvideo2xfMat85_U0_start_full_n");
    sc_trace(mVcdFile, AXIvideo2xfMat85_U0_start_write, "AXIvideo2xfMat85_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_start_full_n, "AXIvideo2xfMat86_U0_start_full_n");
    sc_trace(mVcdFile, AXIvideo2xfMat86_U0_start_write, "AXIvideo2xfMat86_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_start_full_n, "AXIvideo2xfMat_U0_start_full_n");
    sc_trace(mVcdFile, AXIvideo2xfMat_U0_start_write, "AXIvideo2xfMat_U0_start_write");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo87_U0_din, "start_for_xfMat2AXIvideo87_U0_din");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo87_U0_full_n, "start_for_xfMat2AXIvideo87_U0_full_n");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo87_U0_dout, "start_for_xfMat2AXIvideo87_U0_dout");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo87_U0_empty_n, "start_for_xfMat2AXIvideo87_U0_empty_n");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo_U0_din, "start_for_xfMat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo_U0_full_n, "start_for_xfMat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo_U0_dout, "start_for_xfMat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_xfMat2AXIvideo_U0_empty_n, "start_for_xfMat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_start_full_n, "xfMat2AXIvideo87_U0_start_full_n");
    sc_trace(mVcdFile, xfMat2AXIvideo87_U0_start_write, "xfMat2AXIvideo87_U0_start_write");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_start_full_n, "xfMat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, xfMat2AXIvideo_U0_start_write, "xfMat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("blendTop.hdltvin.dat");
    mHdltvoutHandle.open("blendTop.hdltvout.dat");
}

blendTop::~blendTop() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_proc_U0;
    delete AXIvideo2xfMat84_U0;
    delete AXIvideo2xfMat85_U0;
    delete AXIvideo2xfMat86_U0;
    delete AXIvideo2xfMat_U0;
    delete blendL_U0;
    delete xfMat2AXIvideo87_U0;
    delete xfMat2AXIvideo_U0;
    delete pyrLA0_rows_c_U;
    delete pyrLA0_cols_c_U;
    delete pyrLA1_rows_c_U;
    delete pyrLA1_rows_c4_U;
    delete pyrLA1_cols_c_U;
    delete pyrLA1_cols_c5_U;
    delete pyrLA0_data_V_U;
    delete pyrLA0_rows_c6_U;
    delete pyrLA0_cols_c7_U;
    delete pyrLA1_data_V_U;
    delete pyrLB0_data_V_U;
    delete pyrLB1_data_V_U;
    delete pyrS0_data_V_U;
    delete pyrS1_data_V_U;
    delete start_for_blendL_U0_U;
    delete start_for_xfMat2AIfE_U;
    delete start_for_xfMat2AJfO_U;
}

void blendTop::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void blendTop::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2xfMat84_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2xfMat84_U0_ap_ready_count = (!AXIvideo2xfMat84_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat84_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2xfMat84_U0_ap_ready.read()))) {
        AXIvideo2xfMat84_U0_ap_ready_count = (!AXIvideo2xfMat84_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat84_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2xfMat85_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2xfMat85_U0_ap_ready_count = (!AXIvideo2xfMat85_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat85_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2xfMat85_U0_ap_ready.read()))) {
        AXIvideo2xfMat85_U0_ap_ready_count = (!AXIvideo2xfMat85_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat85_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2xfMat86_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2xfMat86_U0_ap_ready_count = (!AXIvideo2xfMat86_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat86_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2xfMat86_U0_ap_ready.read()))) {
        AXIvideo2xfMat86_U0_ap_ready_count = (!AXIvideo2xfMat86_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat86_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2xfMat_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2xfMat_U0_ap_ready_count = (!AXIvideo2xfMat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2xfMat_U0_ap_ready.read()))) {
        AXIvideo2xfMat_U0_ap_ready_count = (!AXIvideo2xfMat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2xfMat_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready = ap_sync_AXIvideo2xfMat84_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready = ap_sync_AXIvideo2xfMat85_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready = ap_sync_AXIvideo2xfMat86_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2xfMat_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2xfMat_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2xfMat_U0_ap_ready = ap_sync_AXIvideo2xfMat_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_sync_Block_proc_U0_ap_ready.read();
        }
    }
}

void blendTop::thread_AXIvideo2xfMat84_U0_ap_continue() {
    AXIvideo2xfMat84_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat84_U0_ap_start() {
    AXIvideo2xfMat84_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendTop::thread_AXIvideo2xfMat84_U0_start_full_n() {
    AXIvideo2xfMat84_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat84_U0_start_write() {
    AXIvideo2xfMat84_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_AXIvideo2xfMat85_U0_ap_continue() {
    AXIvideo2xfMat85_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat85_U0_ap_start() {
    AXIvideo2xfMat85_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendTop::thread_AXIvideo2xfMat85_U0_start_full_n() {
    AXIvideo2xfMat85_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat85_U0_start_write() {
    AXIvideo2xfMat85_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_AXIvideo2xfMat86_U0_ap_continue() {
    AXIvideo2xfMat86_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat86_U0_ap_start() {
    AXIvideo2xfMat86_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendTop::thread_AXIvideo2xfMat86_U0_start_full_n() {
    AXIvideo2xfMat86_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat86_U0_start_write() {
    AXIvideo2xfMat86_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_AXIvideo2xfMat_U0_ap_continue() {
    AXIvideo2xfMat_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat_U0_ap_start() {
    AXIvideo2xfMat_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2xfMat_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendTop::thread_AXIvideo2xfMat_U0_start_full_n() {
    AXIvideo2xfMat_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_AXIvideo2xfMat_U0_start_write() {
    AXIvideo2xfMat_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void blendTop::thread_ap_done() {
    ap_done = ap_sync_done.read();
}

void blendTop::thread_ap_idle() {
    ap_idle = (Block_proc_U0_ap_idle.read() & AXIvideo2xfMat84_U0_ap_idle.read() & AXIvideo2xfMat85_U0_ap_idle.read() & AXIvideo2xfMat86_U0_ap_idle.read() & AXIvideo2xfMat_U0_ap_idle.read() & blendL_U0_ap_idle.read() & xfMat2AXIvideo87_U0_ap_idle.read() & xfMat2AXIvideo_U0_ap_idle.read());
}

void blendTop::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void blendTop::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void blendTop::thread_ap_sync_AXIvideo2xfMat84_U0_ap_ready() {
    ap_sync_AXIvideo2xfMat84_U0_ap_ready = (AXIvideo2xfMat84_U0_ap_ready.read() | ap_sync_reg_AXIvideo2xfMat84_U0_ap_ready.read());
}

void blendTop::thread_ap_sync_AXIvideo2xfMat85_U0_ap_ready() {
    ap_sync_AXIvideo2xfMat85_U0_ap_ready = (AXIvideo2xfMat85_U0_ap_ready.read() | ap_sync_reg_AXIvideo2xfMat85_U0_ap_ready.read());
}

void blendTop::thread_ap_sync_AXIvideo2xfMat86_U0_ap_ready() {
    ap_sync_AXIvideo2xfMat86_U0_ap_ready = (AXIvideo2xfMat86_U0_ap_ready.read() | ap_sync_reg_AXIvideo2xfMat86_U0_ap_ready.read());
}

void blendTop::thread_ap_sync_AXIvideo2xfMat_U0_ap_ready() {
    ap_sync_AXIvideo2xfMat_U0_ap_ready = (AXIvideo2xfMat_U0_ap_ready.read() | ap_sync_reg_AXIvideo2xfMat_U0_ap_ready.read());
}

void blendTop::thread_ap_sync_Block_proc_U0_ap_ready() {
    ap_sync_Block_proc_U0_ap_ready = (Block_proc_U0_ap_ready.read() | ap_sync_reg_Block_proc_U0_ap_ready.read());
}

void blendTop::thread_ap_sync_continue() {
    ap_sync_continue = ap_sync_done.read();
}

void blendTop::thread_ap_sync_done() {
    ap_sync_done = (xfMat2AXIvideo87_U0_ap_done.read() & xfMat2AXIvideo_U0_ap_done.read());
}

void blendTop::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_proc_U0_ap_ready.read() & ap_sync_AXIvideo2xfMat84_U0_ap_ready.read() & ap_sync_AXIvideo2xfMat85_U0_ap_ready.read() & ap_sync_AXIvideo2xfMat86_U0_ap_ready.read() & ap_sync_AXIvideo2xfMat_U0_ap_ready.read());
}

void blendTop::thread_blendL_U0_ap_continue() {
    blendL_U0_ap_continue = ap_const_logic_1;
}

void blendTop::thread_blendL_U0_ap_start() {
    blendL_U0_ap_start = start_for_blendL_U0_empty_n.read();
}

void blendTop::thread_blendL_U0_start_full_n() {
    blendL_U0_start_full_n = (start_for_xfMat2AXIvideo87_U0_full_n.read() & start_for_xfMat2AXIvideo_U0_full_n.read());
}

void blendTop::thread_p_pyrLA0_TREADY() {
    p_pyrLA0_TREADY = AXIvideo2xfMat84_U0_p_pyrLA0_TREADY.read();
}

void blendTop::thread_p_pyrLA1_TREADY() {
    p_pyrLA1_TREADY = AXIvideo2xfMat85_U0_p_pyrLA1_TREADY.read();
}

void blendTop::thread_p_pyrLB0_TREADY() {
    p_pyrLB0_TREADY = AXIvideo2xfMat86_U0_p_pyrLB0_TREADY.read();
}

void blendTop::thread_p_pyrLB1_TREADY() {
    p_pyrLB1_TREADY = AXIvideo2xfMat_U0_p_pyrLB1_TREADY.read();
}

void blendTop::thread_p_pyrS0_TDATA() {
    p_pyrS0_TDATA = xfMat2AXIvideo87_U0_p_pyrS0_TDATA.read();
}

void blendTop::thread_p_pyrS0_TDEST() {
    p_pyrS0_TDEST = xfMat2AXIvideo87_U0_p_pyrS0_TDEST.read();
}

void blendTop::thread_p_pyrS0_TID() {
    p_pyrS0_TID = xfMat2AXIvideo87_U0_p_pyrS0_TID.read();
}

void blendTop::thread_p_pyrS0_TKEEP() {
    p_pyrS0_TKEEP = xfMat2AXIvideo87_U0_p_pyrS0_TKEEP.read();
}

void blendTop::thread_p_pyrS0_TLAST() {
    p_pyrS0_TLAST = xfMat2AXIvideo87_U0_p_pyrS0_TLAST.read();
}

void blendTop::thread_p_pyrS0_TSTRB() {
    p_pyrS0_TSTRB = xfMat2AXIvideo87_U0_p_pyrS0_TSTRB.read();
}

void blendTop::thread_p_pyrS0_TUSER() {
    p_pyrS0_TUSER = xfMat2AXIvideo87_U0_p_pyrS0_TUSER.read();
}

void blendTop::thread_p_pyrS0_TVALID() {
    p_pyrS0_TVALID = xfMat2AXIvideo87_U0_p_pyrS0_TVALID.read();
}

void blendTop::thread_p_pyrS1_TDATA() {
    p_pyrS1_TDATA = xfMat2AXIvideo_U0_p_pyrS1_TDATA.read();
}

void blendTop::thread_p_pyrS1_TDEST() {
    p_pyrS1_TDEST = xfMat2AXIvideo_U0_p_pyrS1_TDEST.read();
}

void blendTop::thread_p_pyrS1_TID() {
    p_pyrS1_TID = xfMat2AXIvideo_U0_p_pyrS1_TID.read();
}

void blendTop::thread_p_pyrS1_TKEEP() {
    p_pyrS1_TKEEP = xfMat2AXIvideo_U0_p_pyrS1_TKEEP.read();
}

void blendTop::thread_p_pyrS1_TLAST() {
    p_pyrS1_TLAST = xfMat2AXIvideo_U0_p_pyrS1_TLAST.read();
}

void blendTop::thread_p_pyrS1_TSTRB() {
    p_pyrS1_TSTRB = xfMat2AXIvideo_U0_p_pyrS1_TSTRB.read();
}

void blendTop::thread_p_pyrS1_TUSER() {
    p_pyrS1_TUSER = xfMat2AXIvideo_U0_p_pyrS1_TUSER.read();
}

void blendTop::thread_p_pyrS1_TVALID() {
    p_pyrS1_TVALID = xfMat2AXIvideo_U0_p_pyrS1_TVALID.read();
}

void blendTop::thread_start_for_blendL_U0_din() {
    start_for_blendL_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void blendTop::thread_start_for_xfMat2AXIvideo87_U0_din() {
    start_for_xfMat2AXIvideo87_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void blendTop::thread_start_for_xfMat2AXIvideo_U0_din() {
    start_for_xfMat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void blendTop::thread_xfMat2AXIvideo87_U0_ap_continue() {
    xfMat2AXIvideo87_U0_ap_continue = ap_sync_done.read();
}

void blendTop::thread_xfMat2AXIvideo87_U0_ap_start() {
    xfMat2AXIvideo87_U0_ap_start = start_for_xfMat2AXIvideo87_U0_empty_n.read();
}

void blendTop::thread_xfMat2AXIvideo87_U0_start_full_n() {
    xfMat2AXIvideo87_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_xfMat2AXIvideo87_U0_start_write() {
    xfMat2AXIvideo87_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_xfMat2AXIvideo_U0_ap_continue() {
    xfMat2AXIvideo_U0_ap_continue = ap_sync_done.read();
}

void blendTop::thread_xfMat2AXIvideo_U0_ap_start() {
    xfMat2AXIvideo_U0_ap_start = start_for_xfMat2AXIvideo_U0_empty_n.read();
}

void blendTop::thread_xfMat2AXIvideo_U0_start_full_n() {
    xfMat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void blendTop::thread_xfMat2AXIvideo_U0_start_write() {
    xfMat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void blendTop::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"p_pyrLA0_TDATA\" :  \"" << p_pyrLA0_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TKEEP\" :  \"" << p_pyrLA0_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TSTRB\" :  \"" << p_pyrLA0_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TUSER\" :  \"" << p_pyrLA0_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TLAST\" :  \"" << p_pyrLA0_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TID\" :  \"" << p_pyrLA0_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TDEST\" :  \"" << p_pyrLA0_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TDATA\" :  \"" << p_pyrLA1_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TKEEP\" :  \"" << p_pyrLA1_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TSTRB\" :  \"" << p_pyrLA1_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TUSER\" :  \"" << p_pyrLA1_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TLAST\" :  \"" << p_pyrLA1_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TID\" :  \"" << p_pyrLA1_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TDEST\" :  \"" << p_pyrLA1_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TDATA\" :  \"" << p_pyrLB0_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TKEEP\" :  \"" << p_pyrLB0_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TSTRB\" :  \"" << p_pyrLB0_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TUSER\" :  \"" << p_pyrLB0_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TLAST\" :  \"" << p_pyrLB0_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TID\" :  \"" << p_pyrLB0_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TDEST\" :  \"" << p_pyrLB0_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TDATA\" :  \"" << p_pyrLB1_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TKEEP\" :  \"" << p_pyrLB1_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TSTRB\" :  \"" << p_pyrLB1_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TUSER\" :  \"" << p_pyrLB1_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TLAST\" :  \"" << p_pyrLB1_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TID\" :  \"" << p_pyrLB1_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TDEST\" :  \"" << p_pyrLB1_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"p_pyrS0_TDATA\" :  \"" << p_pyrS0_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TKEEP\" :  \"" << p_pyrS0_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TSTRB\" :  \"" << p_pyrS0_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TUSER\" :  \"" << p_pyrS0_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TLAST\" :  \"" << p_pyrS0_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TID\" :  \"" << p_pyrS0_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TDEST\" :  \"" << p_pyrS0_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TDATA\" :  \"" << p_pyrS1_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TKEEP\" :  \"" << p_pyrS1_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TSTRB\" :  \"" << p_pyrS1_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TUSER\" :  \"" << p_pyrS1_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TLAST\" :  \"" << p_pyrS1_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TID\" :  \"" << p_pyrS1_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TDEST\" :  \"" << p_pyrS1_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA0_TVALID\" :  \"" << p_pyrLA0_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrLA0_TREADY\" :  \"" << p_pyrLA0_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLA1_TVALID\" :  \"" << p_pyrLA1_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrLA1_TREADY\" :  \"" << p_pyrLA1_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB0_TVALID\" :  \"" << p_pyrLB0_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrLB0_TREADY\" :  \"" << p_pyrLB0_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrLB1_TVALID\" :  \"" << p_pyrLB1_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrLB1_TREADY\" :  \"" << p_pyrLB1_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS0_TVALID\" :  \"" << p_pyrS0_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrS0_TREADY\" :  \"" << p_pyrS0_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"p_pyrS1_TVALID\" :  \"" << p_pyrS1_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"p_pyrS1_TREADY\" :  \"" << p_pyrS1_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

