// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _blendOpt_480_640_83_HH_
#define _blendOpt_480_640_83_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "blendOpt83_Block_pr.h"
#include "blendOpt83_Loop_1_pr.h"
#include "xFPyrDownGaussianBlu.h"
#include "blendOpt83_Loop_2_pr.h"
#include "fifo_w10_d2_A.h"
#include "fifo_w11_d2_A.h"
#include "fifo_w8_d2_A.h"
#include "start_for_xFPyrDoDeQ.h"
#include "start_for_blendOpEe0.h"

namespace ap_rtl {

struct blendOpt_480_640_83 : public sc_module {
    // Port declarations 22
    sc_in< sc_lv<10> > imageA_rows_dout;
    sc_in< sc_logic > imageA_rows_empty_n;
    sc_out< sc_logic > imageA_rows_read;
    sc_in< sc_lv<11> > imageA_cols_dout;
    sc_in< sc_logic > imageA_cols_empty_n;
    sc_out< sc_logic > imageA_cols_read;
    sc_in< sc_lv<8> > imageA_data_V_dout;
    sc_in< sc_logic > imageA_data_V_empty_n;
    sc_out< sc_logic > imageA_data_V_read;
    sc_in< sc_lv<8> > imageB_data_V_dout;
    sc_in< sc_logic > imageB_data_V_empty_n;
    sc_out< sc_logic > imageB_data_V_read;
    sc_out< sc_lv<8> > imageS_data_V_din;
    sc_in< sc_logic > imageS_data_V_full_n;
    sc_out< sc_logic > imageS_data_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    blendOpt_480_640_83(sc_module_name name);
    SC_HAS_PROCESS(blendOpt_480_640_83);

    ~blendOpt_480_640_83();

    sc_trace_file* mVcdFile;

    blendOpt83_Block_pr* blendOpt83_Block_pr_U0;
    blendOpt83_Loop_1_pr* blendOpt83_Loop_1_pr_U0;
    xFPyrDownGaussianBlu* xFPyrDownGaussianBlu_U0;
    blendOpt83_Loop_2_pr* blendOpt83_Loop_2_pr_U0;
    fifo_w10_d2_A* imageA_rows_load3_lo_2_U;
    fifo_w11_d2_A* imageA_cols_load4_lo_2_U;
    fifo_w8_d2_A* p_imageA_in_V_V_U;
    fifo_w8_d2_A* p_imageB_in_V_V_U;
    fifo_w10_d2_A* imageA_rows_load3_lo_1_U;
    fifo_w11_d2_A* imageA_cols_load4_lo_1_U;
    fifo_w8_d2_A* p_imageS_out_V_V_U;
    fifo_w10_d2_A* imageA_rows_load3_lo_U;
    fifo_w11_d2_A* imageA_cols_load4_lo_U;
    start_for_xFPyrDoDeQ* start_for_xFPyrDoDeQ_U;
    start_for_blendOpEe0* start_for_blendOpEe0_U;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_ap_start;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_ap_done;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_ap_continue;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_ap_idle;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_ap_ready;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_imageA_rows_read;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_imageA_cols_read;
    sc_signal< sc_lv<10> > blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_din;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_imageA_rows_load3_out_out_write;
    sc_signal< sc_lv<11> > blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_din;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_imageA_cols_load4_out_out_write;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_ap_start;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_ap_done;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_ap_continue;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_ap_idle;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_ap_ready;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_start_out;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_start_write;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_read;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_read;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageA_data_V_read;
    sc_signal< sc_lv<8> > blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_din;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_p_imageA_in_V_V_write;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageB_data_V_read;
    sc_signal< sc_lv<8> > blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_din;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_p_imageB_in_V_V_write;
    sc_signal< sc_lv<10> > blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_din;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageA_rows_load3_loc_out_write;
    sc_signal< sc_lv<11> > blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_din;
    sc_signal< sc_logic > blendOpt83_Loop_1_pr_U0_imageA_cols_load4_loc_out_write;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_ap_start;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_ap_done;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_ap_continue;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_ap_idle;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_ap_ready;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_start_out;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_start_write;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_p_imageA_in_V_V_read;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_p_imageB_in_V_V_read;
    sc_signal< sc_lv<8> > xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_din;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_p_imageS_out_V_V_write;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_read;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_read;
    sc_signal< sc_lv<10> > xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_din;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_imageA_rows_load3_loc_out_write;
    sc_signal< sc_lv<11> > xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_din;
    sc_signal< sc_logic > xFPyrDownGaussianBlu_U0_imageA_cols_load4_loc_out_write;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_ap_start;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_ap_done;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_ap_continue;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_ap_idle;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_ap_ready;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_imageA_rows_load3_loc_read;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_imageA_cols_load4_loc_read;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_p_imageS_out_V_V_read;
    sc_signal< sc_lv<8> > blendOpt83_Loop_2_pr_U0_imageS_data_V_din;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_imageS_data_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > imageA_rows_load3_lo_2_full_n;
    sc_signal< sc_lv<10> > imageA_rows_load3_lo_2_dout;
    sc_signal< sc_logic > imageA_rows_load3_lo_2_empty_n;
    sc_signal< sc_logic > imageA_cols_load4_lo_2_full_n;
    sc_signal< sc_lv<11> > imageA_cols_load4_lo_2_dout;
    sc_signal< sc_logic > imageA_cols_load4_lo_2_empty_n;
    sc_signal< sc_logic > p_imageA_in_V_V_full_n;
    sc_signal< sc_lv<8> > p_imageA_in_V_V_dout;
    sc_signal< sc_logic > p_imageA_in_V_V_empty_n;
    sc_signal< sc_logic > p_imageB_in_V_V_full_n;
    sc_signal< sc_lv<8> > p_imageB_in_V_V_dout;
    sc_signal< sc_logic > p_imageB_in_V_V_empty_n;
    sc_signal< sc_logic > imageA_rows_load3_lo_1_full_n;
    sc_signal< sc_lv<10> > imageA_rows_load3_lo_1_dout;
    sc_signal< sc_logic > imageA_rows_load3_lo_1_empty_n;
    sc_signal< sc_logic > imageA_cols_load4_lo_1_full_n;
    sc_signal< sc_lv<11> > imageA_cols_load4_lo_1_dout;
    sc_signal< sc_logic > imageA_cols_load4_lo_1_empty_n;
    sc_signal< sc_logic > p_imageS_out_V_V_full_n;
    sc_signal< sc_lv<8> > p_imageS_out_V_V_dout;
    sc_signal< sc_logic > p_imageS_out_V_V_empty_n;
    sc_signal< sc_logic > imageA_rows_load3_lo_full_n;
    sc_signal< sc_lv<10> > imageA_rows_load3_lo_dout;
    sc_signal< sc_logic > imageA_rows_load3_lo_empty_n;
    sc_signal< sc_logic > imageA_cols_load4_lo_full_n;
    sc_signal< sc_lv<11> > imageA_cols_load4_lo_dout;
    sc_signal< sc_logic > imageA_cols_load4_lo_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_blendOpt83_Block_pr_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_blendOpt83_Block_pr_U0_ap_ready;
    sc_signal< sc_lv<2> > blendOpt83_Block_pr_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_blendOpt83_Loop_1_pr_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready;
    sc_signal< sc_lv<2> > blendOpt83_Loop_1_pr_U0_ap_ready_count;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_start_full_n;
    sc_signal< sc_logic > blendOpt83_Block_pr_U0_start_write;
    sc_signal< sc_lv<1> > start_for_xFPyrDownGaussianBlu_U0_din;
    sc_signal< sc_logic > start_for_xFPyrDownGaussianBlu_U0_full_n;
    sc_signal< sc_lv<1> > start_for_xFPyrDownGaussianBlu_U0_dout;
    sc_signal< sc_logic > start_for_xFPyrDownGaussianBlu_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_blendOpt83_Loop_2_pr_U0_din;
    sc_signal< sc_logic > start_for_blendOpt83_Loop_2_pr_U0_full_n;
    sc_signal< sc_lv<1> > start_for_blendOpt83_Loop_2_pr_U0_dout;
    sc_signal< sc_logic > start_for_blendOpt83_Loop_2_pr_U0_empty_n;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_start_full_n;
    sc_signal< sc_logic > blendOpt83_Loop_2_pr_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_blendOpt83_Block_pr_U0_ap_ready();
    void thread_ap_sync_blendOpt83_Loop_1_pr_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_blendOpt83_Block_pr_U0_ap_continue();
    void thread_blendOpt83_Block_pr_U0_ap_start();
    void thread_blendOpt83_Block_pr_U0_start_full_n();
    void thread_blendOpt83_Block_pr_U0_start_write();
    void thread_blendOpt83_Loop_1_pr_U0_ap_continue();
    void thread_blendOpt83_Loop_1_pr_U0_ap_start();
    void thread_blendOpt83_Loop_2_pr_U0_ap_continue();
    void thread_blendOpt83_Loop_2_pr_U0_ap_start();
    void thread_blendOpt83_Loop_2_pr_U0_start_full_n();
    void thread_blendOpt83_Loop_2_pr_U0_start_write();
    void thread_imageA_cols_read();
    void thread_imageA_data_V_read();
    void thread_imageA_rows_read();
    void thread_imageB_data_V_read();
    void thread_imageS_data_V_din();
    void thread_imageS_data_V_write();
    void thread_start_for_blendOpt83_Loop_2_pr_U0_din();
    void thread_start_for_xFPyrDownGaussianBlu_U0_din();
    void thread_xFPyrDownGaussianBlu_U0_ap_continue();
    void thread_xFPyrDownGaussianBlu_U0_ap_start();
};

}

using namespace ap_rtl;

#endif
