// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _xFPyrDownGaussianBlu_HH_
#define _xFPyrDownGaussianBlu_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "xf_pyrdown_gaussian_s.h"

namespace ap_rtl {

struct xFPyrDownGaussianBlu : public sc_module {
    // Port declarations 31
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<8> > p_imageA_in_V_V_dout;
    sc_in< sc_logic > p_imageA_in_V_V_empty_n;
    sc_out< sc_logic > p_imageA_in_V_V_read;
    sc_in< sc_lv<8> > p_imageB_in_V_V_dout;
    sc_in< sc_logic > p_imageB_in_V_V_empty_n;
    sc_out< sc_logic > p_imageB_in_V_V_read;
    sc_out< sc_lv<8> > p_imageS_out_V_V_din;
    sc_in< sc_logic > p_imageS_out_V_V_full_n;
    sc_out< sc_logic > p_imageS_out_V_V_write;
    sc_in< sc_lv<10> > imageA_rows_load3_loc_dout;
    sc_in< sc_logic > imageA_rows_load3_loc_empty_n;
    sc_out< sc_logic > imageA_rows_load3_loc_read;
    sc_in< sc_lv<11> > imageA_cols_load4_loc_dout;
    sc_in< sc_logic > imageA_cols_load4_loc_empty_n;
    sc_out< sc_logic > imageA_cols_load4_loc_read;
    sc_out< sc_lv<10> > imageA_rows_load3_loc_out_din;
    sc_in< sc_logic > imageA_rows_load3_loc_out_full_n;
    sc_out< sc_logic > imageA_rows_load3_loc_out_write;
    sc_out< sc_lv<11> > imageA_cols_load4_loc_out_din;
    sc_in< sc_logic > imageA_cols_load4_loc_out_full_n;
    sc_out< sc_logic > imageA_cols_load4_loc_out_write;


    // Module declarations
    xFPyrDownGaussianBlu(sc_module_name name);
    SC_HAS_PROCESS(xFPyrDownGaussianBlu);

    ~xFPyrDownGaussianBlu();

    sc_trace_file* mVcdFile;

    xf_pyrdown_gaussian_s* grp_xf_pyrdown_gaussian_s_fu_66;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > imageA_rows_load3_loc_blk_n;
    sc_signal< sc_logic > imageA_cols_load4_loc_blk_n;
    sc_signal< sc_logic > imageA_rows_load3_loc_out_blk_n;
    sc_signal< sc_logic > imageA_cols_load4_loc_out_blk_n;
    sc_signal< sc_lv<10> > imageA_rows_load3_lo_reg_80;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<11> > imageA_cols_load4_lo_reg_85;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_ap_start;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_ap_done;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_ap_idle;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_ap_ready;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_p_src_mat_A_V_V_read;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_p_src_mat_B_V_V_read;
    sc_signal< sc_lv<8> > grp_xf_pyrdown_gaussian_s_fu_66_p_out_mat_V_V_din;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_p_out_mat_V_V_write;
    sc_signal< sc_logic > grp_xf_pyrdown_gaussian_s_fu_66_ap_start_reg;
    sc_signal< bool > ap_block_state1_ignore_call11;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state1_ignore_call11();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_xf_pyrdown_gaussian_s_fu_66_ap_start();
    void thread_imageA_cols_load4_loc_blk_n();
    void thread_imageA_cols_load4_loc_out_blk_n();
    void thread_imageA_cols_load4_loc_out_din();
    void thread_imageA_cols_load4_loc_out_write();
    void thread_imageA_cols_load4_loc_read();
    void thread_imageA_rows_load3_loc_blk_n();
    void thread_imageA_rows_load3_loc_out_blk_n();
    void thread_imageA_rows_load3_loc_out_din();
    void thread_imageA_rows_load3_loc_out_write();
    void thread_imageA_rows_load3_loc_read();
    void thread_internal_ap_ready();
    void thread_p_imageA_in_V_V_read();
    void thread_p_imageB_in_V_V_read();
    void thread_p_imageS_out_V_V_din();
    void thread_p_imageS_out_V_V_write();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
